export type Lang = 'en' | 'ar';
export type Kind = 'class' | 'task' | 'focus' | 'habit';

const en = {
  appName: 'Nazzim', splashTag: 'From academic chaos to a clear plan.',
  splashParts: ['Plan', 'Focus', 'Exams', 'Progress'], madeIn: 'Made in Oman', aSkip: 'Skip',
  dateLine: 'MONDAY · 11 MAY', greet: 'Morning, ', now: 'NOW', nowRange: '10:30 – 11:15',
  nowTitle: 'Review Chapter 3 — Calculus', nowMeta: 'Maths · 35 min left · exam in 3 days',
  startFocus: 'Start focus', markDone: 'Done',
  aiTag: 'NAZZIM AI · BETA', aiLine: 'Your exam is in 3 days. I moved your hardest block to 10:30 — the hour you focus best.',
  stream: 'Today', kClass: 'Class', kTask: 'Task', kFocus: 'Focus', kHabit: 'Habit',
  plan: 'Plan', planSub: 'Calendar, tasks and exams — one view', exams: 'EXAMS', daysLeft: 'days left',
  planExamCta: 'Plan a new exam in one sentence', weekTasks: 'THIS WEEK',
  focus: 'Focus', focusOn: 'FOCUSING ON', ready: 'READY', inFocus: 'IN FOCUS', paused: 'PAUSED',
  sound: 'Sound', sounds: ['Off', 'Rain', 'Café'], lock: 'Silence other apps', lockSub: 'Blocks social apps while you focus',
  me: 'Progress', meSub: 'How your semester is going', level: 'LEVEL', rank: 'Focused scholar',
  stFocus: 'Focus hours', stDone: 'Tasks done', stTrend: 'Vs last week',
  week: 'This week', weekSub: 'Focus minutes', habits: 'Habits', habitsHint: 'Tap a day',
  language: 'Language', langValue: 'English', proValue: '7 days free',
  appearance: 'Appearance', appearances: ['System', 'Light', 'Dark'],
  accentColor: 'App colour', accentNames: ['Blue', 'Pink', 'Violet', 'Teal'],
  reminders: 'Reminders', remindersSub: 'Habits, exams and focus sessions',
  remHabits: 'Daily plan reminder', remExams: 'Exam countdown', remExamsSub: 'The evening before, at 19:00',
  remFocus: 'Focus session ends', remFocusSub: 'Even when Nazzim is closed',
  remDenied: 'Notifications are off for Nazzim. Turn them on in Settings › Nazzim › Notifications.',
  remWeb: 'Reminders work in the iPhone and iPad app.',
  nHabitTitle: 'Your next move is ready', nHabitBody: 'Open Nazzim to see what to study now.',
  nExamTitle: '{name} exam tomorrow', nExamBody: 'Look over your plan and sleep before midnight.',
  nFocusTitle: 'Focus session complete', nFocusBody: '{task} · +50 XP',
  badgesN: ['7-day streak', 'Early bird', '50h focus', 'Exam ready'],
  cmdTitle: 'What’s coming up?', cmdPh: 'e.g. Physics exam on Thursday', tryThis: 'TRY',
  quick: ['Physics exam on Thursday', 'Add task: lab report by Wednesday', 'Gym 3 times a week'],
  building: 'Nazzim is building your plan…', built: 'BUILT FROM ONE SENTENCE', builtCount: '5 items',
  addAll: 'Add all to my plan',
  gen: [
    ['Summarise chapters 4–6', 'Today · 16:00 · 40 min', 'task'],
    ['Problem session 1', 'Tue · 11:00 · 50 min', 'focus'],
    ['Past paper 2024', 'Wed · 14:00 · 90 min', 'task'],
    ['Sleep before midnight', 'Until Thursday', 'habit'],
    ['Physics exam', 'Thu · 09:00 · Hall C', 'class'],
  ] as [string, string, Kind][],
  toastTask: 'Task done · +20 XP', toastHabit: 'Habit kept · +10 XP', toastFocus: 'Session complete · +50 XP', toastAdded: 'Revision plan built · +30 XP',
  tabToday: 'Today', tabPlan: 'Plan', tabFocus: 'Focus', tabMe: 'Progress',
  dow: ['S', 'M', 'T', 'W', 'T', 'F', 'S'],
  min: 'min', of: 'of', done: 'done', xpTo: 'XP to level', streakSuffix: 'd',
  profile: 'Profile', editProfile: 'Edit profile', saveProfile: 'Save', fName: 'Name', fUni: 'University', fMajor: 'Major', fYear: 'Year',
  defaultName: 'Ahmed', defaultUni: 'Sultan Qaboos University', defaultMajor: 'Computer Science', defaultYear: 'Year 2',
  dayStreak: 'Day streak', yourPlan: 'YOUR PLAN', manage: 'Manage', upgrade: 'Upgrade', memberSince: 'Studying with Nazzim since May',
  settings: 'Settings', sGeneral: 'GENERAL', sControls: 'CONTROLS', sAccount: 'PRIVACY & ACCOUNT', version: 'Nazzim 1.0.0',
  cHaptics: 'Haptics', cHapticsSub: 'A light tap when you complete something',
  cRewards: 'Rewards & XP', cRewardsSub: 'Levels, streaks and points',
  cAi: 'AI suggestions', cAiSub: 'Show Nazzim AI tips on Today', cFocusLen: 'Default focus length',
  plans: 'Plans', plansSub: 'Everything is free right now — Pro is on the way.', monthly: 'Monthly', yearly: 'Yearly',
  csTitle: 'Pro is coming soon', csBadge: 'Coming soon',
  csSub: 'Every part of Nazzim is free right now. Pro will add power features for students who want more — and you’ll be the first to know.',
  csFreeNow: 'All features are free right now', csWhat: 'What Pro will add', csBack: 'Keep using Nazzim free',
  tiers: {
    free: { name: 'Free', tag: 'Your next move, every day', per: 'forever',
      features: ['Today: what to do right now', 'Subjects, tasks and focus linked to them', 'Smart Planner for 2 active exams', 'Rescue Mode when you fall behind'] },
    plus: { name: 'Plus', tag: 'For a full semester', per: '',
      features: ['Everything in Free', 'Unlimited exams and study plans', 'All progress insights', 'Exam and daily plan reminders'] },
    pro: { name: 'Pro', tag: 'Your semester on autopilot', per: '',
      features: ['Everything in Plus', 'Calendar sync (coming soon)', 'AI study coach (coming soon)', 'Priority support'] },
  },
  perMonth: '/ month', perYear: '/ year', yearNote: '{m} / month, billed yearly', save: 'Save {n}%', bestValue: 'Best value',
  currentPlan: 'Current plan', choose: 'Choose {name}', switchFree: 'Switch to Free',
  trialCta: 'Start 7-day free trial',
  legal: 'Free for 7 days, then {p}. Renews automatically unless cancelled at least 24 hours before the end of the current period. Manage or cancel anytime in Settings › Apple ID › Subscriptions.',
  restore: 'Restore purchases', terms: 'Terms of Use', privacyL: 'Privacy Policy', support: 'Support',
  deleteAcc: 'Delete account', delTitle: 'Delete your account?',
  delBody: 'This permanently erases your account and all its subjects, exams, plans and progress from Nazzim’s servers and this device. This can’t be undone.',
  cancel: 'Cancel', delConfirm: 'Delete permanently', toastDel: 'Account deletion requested',
  exAdd: 'Add exam', exNew: 'New exam', exSubject: 'Subject', exSubjectPh: 'e.g. Physics', exDate: 'Exam date',
  exChapters: 'Chapters or topics', exChaptersPh: 'One per line, e.g.\nChapter 4\nChapter 5', exCreate: 'Build my revision plan',
  exPreview: '{s} sessions over {d} days: study each chapter, review it after 1, 3 and 7 days, then a mock test the day before.',
  exTooSoon: 'Pick a date at least one day away.', exNeedsChapters: 'Add at least one chapter.',
  exReady: 'READY', exLeft: '{c} left', exDelete: 'Delete exam', exDeleteConfirm: 'Tap again to delete',
  exNone: 'No exams yet. Add one and Nazzim plans your revision.', exHow: 'Spaced review: each chapter comes back after 1, 3 and 7 days. Hard adds a review tomorrow; Easy skips one.',
  exChaptersH: 'CHAPTERS', exChaptersN: '{c}', exPlanH: 'REVISION PLAN', exAll: 'All chapters', exDay: 'Exam day',
  // Counted nouns. English needs two forms; Arabic needs four (see `counted` at the foot of this file).
  units: {
    day: ['day', 'days'], session: ['session', 'sessions'], chapter: ['chapter', 'chapters'],
    task: ['task', 'tasks'], minute: ['minute', 'minutes'], card: ['card', 'cards'],
    exam: ['exam', 'exams'],
  },
  // ── Retrieval practice ──
  rcTitle: 'Self-test', rcSub: 'Prove you can recall it', rcOpen: 'Test yourself',
  rcEmpty: 'No cards yet. Write a question you expect on the exam, and the answer in your own words.',
  rcEmptyWhy: 'Writing the card is already studying. Answering it later is what turns your evidence into something that means anything.',
  rcAdd: 'Add a card', rcQ: 'Question', rcQPh: 'e.g. What does the central limit theorem state?',
  rcA: 'Answer', rcAPh: 'In your own words — this is the key you grade yourself against.',
  rcSave: 'Save card', rcChapter: 'Chapter', rcCards: '{c}', rcCardsNone: 'No cards',
  rcDue: '{n} due', rcAllCaught: 'Nothing due right now. Next review {d}.',
  rcYourAnswer: 'Write your answer first', rcYourAnswerPh: 'Recall it before you look. Typing is the practice.',
  rcReveal: 'Show the answer', rcGradeQ: 'How close were you?',
  rcGrades: ['Forgot', 'Almost', 'Knew it'],
  rcSelfNote: 'We found no wording in common with the key. Grade yourself however you judge — if you pick “Knew it” it is recorded as self-reported evidence, which counts for less than a corroborated one.',
  rcDone: 'Self-test finished', rcScore: '{c} of {n} recalled', rcBack: 'Back to the exam',
  rcDelete: 'Delete card', rcNext: 'Next card', rcProgress: '{i} of {n}',
  // ── Evidence completeness, explained ──
  rdWhy: 'Why this number?', rdTitle: 'How evidence completeness is measured', rdEvidence: 'THE EVIDENCE',
  rdIntro: 'This number describes how strong the evidence you have gathered about your preparation is — it is not a prediction of your grade. Each chapter earns it three ways.',
  rdCoverage: 'Chapters studied', rdEffort: 'Focused minutes', rdRecall: 'Recall proven',
  rdEffortVal: '{a} of {b} planned', rdRecallNone: 'Not self-tested yet', rdRecallVal: '{n}% recalled',
  rdCeiling: 'Ticking a block alone caps a chapter at {n}%. Spending the planned minutes in a focus session raises it to {e}%. Only a self-test can take it higher — and a self-test that goes badly lowers it.',
  rdNow: 'Now', rdMax: 'Reachable without new evidence',
  // Short forms for the Today hero: one line, no explanation. The rdNext* sentences above stay for the
  // explainer screen, where there is room to say why.
  evNext: 'NEXT EVIDENCE', evStart: 'Start now', evStudy: 'Study {c}', evFocus: 'Focus on {c}',
  evRecall: 'Self-test {c}', evMock: 'Sit the mock test', evReady: 'Evidence complete',
  evDayDone: 'You finished today’s schedule. This is the strongest next piece of evidence if you want to carry on.',
  evNoExam: 'Add your next exam', evNoExamSub: 'One subject, one date, your chapter names — then Nazzim can tell you what to do first.',
  evWhy: 'Why this number?',
  evBand: ['Little evidence yet — every session and card adds to it', 'Evidence is building — keep testing yourself', 'Strong evidence — keep it fresh before the exam'],
  rdNextStudy: 'Study chapter {c} — it has no work on it yet.',
  rdNextFocus: 'Focus a real session on chapter {c}. It is ticked but barely studied.',
  rdNextRecall: 'Self-test chapter {c}. Recall is the evidence you are missing.',
  rdNextMock: 'Sit the mock test to confirm it.', rdNextReady: 'You are ready. Keep it warm with short reviews.',
  rdDecay: 'Untouched for {n} days — older work counts for a little less.',
  kLearn: 'Study', kReview: 'Review', kMock: 'Mock test', rateQ: 'How well do you know it?', rates: ['Hard', 'OK', 'Easy'],
  reviewsToday: 'REVISION TODAY', onDay: 'SCHEDULE · {d}', nothingDay: 'Nothing planned. A free day.', startS: 'Start', doneS: 'Done',
  dToday: 'today', dTomorrow: 'tomorrow', dIn: 'in {c}', toastRated: 'Saved · +20 XP',
  wd: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'], wdLong: ['SUNDAY', 'MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY'],
  months: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
  sampleExam: { subject: 'Mathematics', chapters: ['Limits', 'Derivatives', 'Chain rule', 'Integrals'] },
  aiExam: { subject: 'Physics', chapters: ['Chapter 4 · Motion', 'Chapter 5 · Forces', 'Chapter 6 · Energy'] },
  seed: {
    subjects: ['Statistics', 'Calculus', 'Physics'], examName: 'Statistics',
    chapters: ['Chapter 1', 'Chapter 2', 'Chapter 3', 'Chapter 4'],
    tasks: ['Chapter 3 practice questions', 'Physics lab report', 'Calculus problem set 2'],
  },
  greetings: ['Good morning', 'Good afternoon', 'Good evening'], nextMove: 'YOUR NEXT MOVE', startSession: 'Start session',
  rOverdue: 'Overdue by {n} days', rOverdue1: 'Overdue since yesterday', rExamSoon: '{exam} exam in {n} days', rExamTomorrow: '{exam} exam tomorrow',
  rDueToday: 'Due today', rDueTomorrow: 'Due tomorrow', rPlanned: 'Part of your study plan',
  nextClear: 'You’re on track for today.', nextClearSub: 'Nothing else is due. Rest, or get ahead on your next exam.',
  nextAdd: 'Add your first exam', nextAddSub: 'NAZZIM builds the study plan for you.',
  overall: 'Semester progress', todaySchedule: 'Today’s schedule', emptyToday: 'Nothing scheduled today.',
  load: 'Academic load', loadLevels: ['Light', 'Moderate', 'Heavy'], loadSub: '{h} planned this week', nextDeadline: 'Next deadline',
  kExam: 'Exam', kTaskB: 'Task', kStudyB: 'Study', markDoneA: 'Mark as done',
  tabSubjects: 'Subjects', tabMore: 'More', subjects: 'Subjects', target: 'Target {g}', addSubject: 'Add subject', newSubject: 'New subject',
  subjName: 'Name', subjNamePh: 'e.g. Statistics', targetGrade: 'Target grade', colour: 'Colour', icon: 'Icon', create: 'Create',
  progressL: 'Progress', nextTask: 'Next study task', tasksL: 'Tasks', pendingN: '{n} pending', examsL: 'Exams', upcomingN: '{n} upcoming',
  studyL: 'Study', sessionsMonth: '{n} sessions this month', addTask: 'Add task', taskTitlePh: 'e.g. Chapter 3 practice questions',
  // ── Tasks: one list, ordered by what deserves attention first ──
  tasksTitle: 'Tasks', tkOpenN: 'Open: {n}', tkSmart: 'Smart order', tkByDue: 'By due date', tkShowDone: 'Show done', tkHideDone: 'Hide done',
  tkGroups: { overdue: 'PAST THEIR DATE', today: 'TODAY', soon: 'THIS WEEK', later: 'LATER', done: 'DONE' },
  tkWhy: { overdue: 'past its date', dueToday: 'due today', plannedToday: 'planned for today', examSoon: 'exam soon', highPriority: 'marked important', dueTomorrow: 'due tomorrow', quickWin: 'quick win', dueLater: '', done: '' },
  tkSmartWhy: 'Past-due tasks come first, then today, then this week. Inside each, what you marked important, what is due sooner and whose subject has an exam coming rise to the top.',
  tkEmptyT: 'No tasks yet', tkEmptyS: 'Type one in a single line — “Statistics essay tomorrow 45m” — and Nazzim fills in the rest.',
  tkQuickPh: 'e.g. Statistics essay tomorrow 45m', tkUnderstood: 'Understood', tkTitleL: 'Title', tkPriority: 'Importance',
  tkPriorities: ['Low', 'Normal', 'High'], tkNotes: 'Notes', tkNotesPh: 'Pages, links, what to submit…', tkDueDate: 'Due date',
  tkEdit: 'Edit task', tkSave: 'Save changes', tkSavedT: 'Task saved', tkMoveTomorrow: 'Do it tomorrow',
  tkMoveNote: 'Moves the day you work on it. The due date stays {d}.', tkMovedT: 'Moved to tomorrow. Still due {d}.',
  tkMarkDone: 'Mark as done', tkMarkOpen: 'Not done yet', tkDelete: 'Delete task', tkDeleteConfirm: 'Tap again to delete',
  tkInvalid: 'That couldn’t be saved. Check the title and the date.', tkPlannedFor: 'Working on it {d}', tkPlusMin: '+5 min', tkMinusMin: '−5 min',
  tkDayEarlier: 'One day earlier', tkDayLater: 'One day later', tkAll: 'All tasks',
  due: 'Due', estimate: 'Time', noSubjects: 'Add your subjects to see your semester in one place.', deleteSubject: 'Delete subject',
  noTasks: 'No tasks yet.', examFor: 'Subject', more: 'More', upcomingExams: 'Upcoming exams', progressMenu: 'Progress',
  inDaysShort: '{n} days left', allClear: 'All clear',
  // Rescue Mode
  limitExams: 'Free covers 2 active exams. Plus plans every exam.',
  freeFocus: 'Free focus',
  studyTimeQ: 'When do you usually study?', studyTimeSub: 'Your daily plan and reminder follow it.', studyTimes: ['Morning', 'Afternoon', 'Evening', 'Night'],
  streakA: '{n} study days in a row', clTitle: 'Getting started', clProgress: '{d} of {t}', clHide: 'Hide',
  clSteps: { semester: 'Set up your semester', focus: 'Finish your first focus session', rate: 'Rate a session or finish a task', reminders: 'Turn on your daily reminder', account: 'Back up with a free account' },
  recapTitle: 'Your last week', recapBody: '{m} focused · {d} study days · {s} sessions done', recapNext: 'This week: {m} planned.', recapCta: 'See this week',
  remAskT: 'Want a nudge tomorrow?', remAskB: 'One reminder at {t} with your next move. Change or turn it off anytime.', remAskYes: 'Remind me', remDailyAt: 'Daily at {t}',
  toastReady: '{exam} evidence {a}% → {b}%',
  toastFocusAway: 'The app was in the background for the whole block, so no focus time was credited.', nDailyBody: 'Next: {t}', nStreakTitle: '{n} study days in a row', nStreakBody: 'A 10-minute session today keeps it going.',
  examToday: 'Exam today', nowL: 'NOW', dayProgress: '{d} of {t} done · {m} left', dayDone: 'Everything for today is done',
  weekAhead: 'THE WEEK AHEAD, IN HOURS', weekClear: 'Nothing planned for the next seven days.',
  glanceSemester: 'Evidence', glanceNoExam: 'Tasks done', glanceWeek: 'Planned ahead', glanceExam: 'Next exam', glanceNone: 'None yet', smartPlan: 'Smart plan',
  emptyTodayT: 'Nothing planned today', emptyTodayS: 'Add a task, or plan an exam and Nazzim fills your days.',
  secAccount: 'ACCOUNT', secStudy: 'STUDY', secApp: 'APP', subjExam: 'Exam {d}', subjTasks: '{c} open', subjClear: 'Nothing due',
  acTitle: 'Account', acSub: 'Sync and back up your semester', acSignIn: 'Sign in', acCreate: 'Create account',
  acBenefits: ['Your semester on every device', 'Backed up if you lose your phone', 'Works offline, syncs when you’re back'],
  acEmail: 'Email', acPassword: 'Password (8+ characters)', acToCreate: 'New here? Create an account', acToSignIn: 'Have an account? Sign in',
  acConfirm: 'Check your inbox and confirm your email, then sign in here.', acLocalNote: 'Without an account, your data stays on this device only.',
  acErr: { invalid: 'Email or password is incorrect.', unconfirmed: 'Confirm your email first (check your inbox).', weak: 'Use at least 8 characters.', exists: 'An account with this email already exists. Sign in instead.', network: 'No connection. Try again.', unavailable: 'Sync isn’t set up in this build.', unknown: 'Something went wrong. Try again.' },
  acSynced: 'Synced {t}', acSyncing: 'Syncing…', acSyncError: 'Couldn’t sync. Your changes are safe on this device.', acNever: 'Not synced yet',
  acSyncNow: 'Sync now', acSignOut: 'Sign out', acSignedIn: 'SIGNED IN AS', acJustNow: 'just now', acMinAgo: '{n} min ago',
  obHaveAccount: 'I already have an account', delLocalTitle: 'Erase data on this device?',
  delLocalBody: 'This erases your subjects, exams, plans and progress from this device. This can’t be undone.', toastDelFail: 'Couldn’t delete. Check your connection.',
  xDaysLeft: '{c} LEFT', xDayLeft: 'TOMORROW', xToday: 'TODAY', xOver: 'DONE', xReadiness: 'Evidence completeness',
  xStatus: { onTrack: 'On track', behind: 'A little behind', atRisk: 'Needs focus now', ready: 'Ready', over: 'Exam finished', unknown: 'Date needs checking' },
  xStatusSub: { onTrack: 'Keep following the plan.', behind: '{n} sessions slipped. Today’s session catches you up.', atRisk: 'Few days left. Do the next session and the mock test.', ready: 'Light reviews and rest before the exam.', over: 'How did it go? Your work counts toward the semester.', unknown: 'This exam’s date could not be read, so nothing is scheduled for it. Set the date again.' },
  xRemaining: 'Left: {s} · {t}', xPerDay: 'About {m} a day', xNextBtn: 'Start next: {t}', xTopics: 'TOPICS', xPlan: 'STUDY PLAN',
  xTopicState: { notStarted: 'Not started', learning: 'In progress', solid: 'Solid', weak: 'Needs work' },
  xPhase: { learn: 'Phase 1 of 3 · First pass', review: 'Phase 2 of 3 · Reviews', final: 'Phase 3 of 3 · Final prep' },
  xMock: 'Mock test {d}: the best predictor of how the exam will go.', xAdjust: 'Change date or chapters', xDoneN: '{n} done',
  xFocusOn: 'Focus here: {t}',
  obTag: 'From academic chaos to a clear plan.', obStart: 'Get started', obSample: 'Explore with a sample semester',
  obStep: 'Step {n} of 3', obAboutT: 'Where do you study?', obAboutS: 'So plans fit your semester. You can skip any field.',
  // Onboarding asks for the three things the evidence model actually needs, and nothing else.
  obSubjOne: 'What is the subject?', obSubjOneS: 'The one with an exam coming up. You can add the rest later.',
  obDateT: 'When is the exam?', obDateS: 'Pick the real date — the whole plan is built backwards from it.',
  obChapT: 'What are its chapters?', obChapS: 'One per line, in your own words. “Confidence intervals” is a far more useful thing to be told to revise than “Chapter 3”.',
  obChapPh: 'Probability\nSampling distributions\nConfidence intervals',
  obGo: 'Show me what to do first', obLater: 'Your name and university can wait — add them any time in Profile.',
  obSubjT: 'Your subjects this semester', obSubjS: 'Add each course and the grade you’re aiming for.', obSubjPh: 'e.g. Statistics',
  obExamT: 'Your next exam', obExamS: 'Nazzim turns it into a day-by-day study plan.', obWhich: 'Subject', obWhen: 'When', obChapters: 'Chapters',
  obBuild: 'Let’s build your semester', obNext: 'Next', obSkip: 'Skip', obNoExam: 'No exam coming up yet', noName: 'Student',
  qaTitle: 'Add', qaTask: 'Task or assignment', qaTaskSub: 'Homework, lab report, reading', qaExam: 'Exam',
  qaExamSub: 'Nazzim builds the study plan', qaSubject: 'Subject', qaSubjectSub: 'A course this semester',
  prSemester: 'Evidence completeness', prConsistency: 'Study consistency', prActive: '{n} of 7 days', prTasks: 'Tasks completed',
  sbReady: 'evidence', sbDone: 'done', prWorkDone: '{n}% of the planned work done',
  toastPurchasePending: 'Confirming with the store…', toastPurchaseOff: 'Subscriptions are not available yet.',
  toastPurchaseCancelled: 'Purchase cancelled.', toastPurchaseFailed: 'The store could not complete that.',
  toastRestored: 'Purchases restored.', toastRestoreNone: 'No purchase found for this account.',
  payOff: 'Nazzim is free while subscriptions are being set up. Everything you see is included.',
  payRestore: 'Restore purchases',
  prReadySub: 'Across the exams still ahead', prNoExams: 'Add an exam to start collecting evidence', prTasksN: '{d} of {t}', prWeek: 'Actually focused', prSubjects: 'SUBJECT PROGRESS', prReady: 'Evidence {n}%', prInsights: 'INSIGHTS',
  prWeekBars: 'FOCUS THIS WEEK', prActiveDays: 'Active days', prNoSubjects: 'Add subjects to see progress per course.',
  iAtRisk: '{exam} is in {n} days and your evidence is at {r}%. Today’s session matters most.', iAtRisk1: '{exam} is tomorrow and your evidence is at {r}%. Do the mock test today.',
  iBehind: '{n} tasks slipped. Rescue Mode can rebuild your week in a minute.', iUp: '{exam} evidence is up {n} points this week.',
  iHeavier: 'Next week is heavier: {n} planned vs {c} this week. Starting early keeps it calm.', iConsistency: 'You studied on {n} of the last 7 days.',
  iStart: 'Finish one session today and your progress starts here.',
  rescueEyebrow: 'TODAY TRIAGE', rescueTitle: 'Today’s time is limited.', rescueSub: 'So let’s put what deserves it first.',
  trNow: 'NOW', trLater: 'LATER', trNowSub: 'Three things, and they fit in a normal day for you.',
  trWhy: { examSoon: 'exam is close', evidenceGap: 'weakest evidence', overdue: 'past its date', dueToday: 'due today' },
  trRebuild: 'Or rebuild the whole week', trNothing: 'Nothing is competing for today’s time.',
  trCapacity: '{a} asked of today · {b} is a normal day for you',
  rOverdueN: '{u} overdue', rExamsN: '{u} ahead', rWorkN: 'of work this week', capacityL: 'On a normal day I can study',
  buildRescue: 'Build Rescue Plan', applyRescue: 'Apply this plan', rescueNote: 'Deadlines stay the same. Only when you do the work changes.',
  rescueOk: 'This fits your time. {n} items move, nothing is lost.', rescueOnTrack: 'You’re on track. Nothing needs to move.',
  rescueTight: 'Some days still run over. Do the flagged items first, or ask for an extension.', rescueDropped: '{n} extra reviews dropped; later reviews cover them.',
  movedFrom: 'from {d}', tightL: 'Over', toastRescue: 'Plan rebuilt. One step at a time.', rescueMenu: 'Today triage',
  behindTitle: 'Today is overcommitted', behindOverdue: '{n} past their date.', behindLoad: 'More is asked of today than a normal day holds.', rebuild: 'Rebuild',
  // Focus linked to work
  sessionComplete: 'Session complete', howWent: 'How did it go? This updates the evidence for this exam.', taskDoneQ: 'Did you finish the task?',
  yesDone: 'Yes, done', notYet: 'Not yet', focusMin: '{n} min focused', rHard: 'Hard', rOk: 'OK', rEasy: 'Easy',
  // Smart Planner
  plEyebrow: 'SMART PLANNER', plTitle: 'Tell Nazzim what you need.', plSub: 'Your exams, your time, one plan.',
  plPh: 'e.g. Statistics exam in 6 days, I haven’t started', plRun: 'Plan it',
  plTry: ['Statistics exam in 6 days, I haven’t started', 'Calculus final next week, 5 chapters', 'Physics quiz on Thursday'],
  plDays: '{n}-day study plan', plWhy: 'WHY THIS PLAN', plApply: 'Add to my plan', plReplaces: 'Replaces your current {s} plan.',
  plNeed: 'Name the subject and when the exam is, e.g. “Physics exam in 5 days”.', plChapters: 'Chapters', plWhen: 'Exam',
  plNewSubject: 'New subject: {s}', plChapterN: 'Chapter {n}', plR1: 'Starts today, {n} days before the exam.',
  plR2: 'Each chapter comes back after 1, 3 and 7 days, the spacing that makes it stick.', plR3: 'A mock test the day before.',
  plR4: 'About {m} a day, inside your {c}.', plR4over: 'About {m} a day, more than your usual {c}. Start today.',
  plR5: 'Placed around {n} things already on your schedule.', plDone: 'Plan added. Your first session is on Today.',
  toastPlan: '{name} is on (demo, no charge)', toastFree: 'Switched to Free', toastSaved: 'Profile saved', aBack: 'Back',
  aNew: 'New plan', aReset: 'Reset timer', aPlay: 'Start or pause focus', aFinish: 'Finish session', aClose: 'Close',
  // UI system: states that every screen shares
  rcYours: 'Your answer',
  rcCheckT: 'Your answer may need a second look',
  rcOverride: 'My answer was right',
  rcOverrideNote: 'Your call is respected and recorded as “Knew it”. Because the wording did not match, it counts as self-reported evidence.',
  rcGradeHint: ['Not recalled — the card comes back tomorrow', 'Partly recalled — the card returns sooner than one you knew', 'Recalled — the gap before it returns grows'],
  rcRevealHint: 'Write something first — the attempt is the practice',
  rcEmptyT: 'No cards yet', rcDeleteConfirm: 'Tap again to delete the card',
  subjEmptyT: 'Start with one subject', subjEmptyS: 'One subject and its next exam is enough for Nazzim to plan your days.',
  offT: 'You’re offline', offS: 'Everything you do is saved on this device.',
  errT: 'This screen hit a problem', errS: 'Your plan is safe on this device. Try again — if it keeps happening, tell us at support@nazzim.app.', errRetry: 'Try again',
};

export type Copy = typeof en;

const ar: Copy = {
  appName: 'نظّم', splashTag: 'من الفوضى الأكاديمية إلى خطة واضحة.',
  splashParts: ['الخطة', 'التركيز', 'الامتحانات', 'التقدم'], madeIn: 'صُنع في عُمان', aSkip: 'تخطي',
  dateLine: 'الاثنين · 11 مايو', greet: 'صباح النور، ', now: 'الآن', nowRange: '10:30 – 11:15',
  nowTitle: 'مراجعة الفصل الثالث — التفاضل', nowMeta: 'رياضيات · متبقٍ 35 دقيقة · الامتحان بعد 3 أيام',
  startFocus: 'ابدأ التركيز', markDone: 'تم',
  aiTag: 'ذكاء نظّم · تجريبي', aiLine: 'امتحانك بعد 3 أيام. نقلت أصعب جلسة إلى 10:30 — الساعة التي تركّز فيها أكثر.',
  stream: 'اليوم', kClass: 'محاضرة', kTask: 'مهمة', kFocus: 'تركيز', kHabit: 'عادة',
  plan: 'الخطة', planSub: 'التقويم والمهام والامتحانات — في شاشة واحدة', exams: 'الامتحانات', daysLeft: 'أيام متبقية',
  planExamCta: 'خطط لامتحان جديد بجملة واحدة', weekTasks: 'هذا الأسبوع',
  focus: 'التركيز', focusOn: 'تركّز على', ready: 'جاهز', inFocus: 'في التركيز', paused: 'متوقف',
  sound: 'الصوت', sounds: ['بدون', 'مطر', 'مقهى'], lock: 'إسكات التطبيقات الأخرى', lockSub: 'يحجب التواصل الاجتماعي أثناء التركيز',
  me: 'التقدم', meSub: 'كيف يسير فصلك الدراسي', level: 'المستوى', rank: 'طالب مركّز',
  stFocus: 'ساعات التركيز', stDone: 'مهام منجزة', stTrend: 'عن الأسبوع الماضي',
  week: 'هذا الأسبوع', weekSub: 'دقائق التركيز', habits: 'العادات', habitsHint: 'اضغط على اليوم',
  language: 'اللغة', langValue: 'العربية', proValue: '7 أيام مجاناً',
  appearance: 'المظهر', appearances: ['تلقائي', 'فاتح', 'داكن'],
  accentColor: 'لون التطبيق', accentNames: ['أزرق', 'وردي', 'بنفسجي', 'فيروزي'],
  reminders: 'التذكيرات', remindersSub: 'العادات والامتحانات وجلسات التركيز',
  remHabits: 'تذكير خطة اليوم', remExams: 'العد التنازلي للامتحان', remExamsSub: 'مساء اليوم السابق، الساعة 19:00',
  remFocus: 'انتهاء جلسة التركيز', remFocusSub: 'حتى لو كان نظّم مغلقاً',
  remDenied: 'الإشعارات مغلقة لتطبيق نظّم. فعّلها من الإعدادات › نظّم › الإشعارات.',
  remWeb: 'التذكيرات تعمل في تطبيق الآيفون والآيباد.',
  nHabitTitle: 'خطوتك التالية جاهزة', nHabitBody: 'افتح نظّم لترى ماذا تذاكر الآن.',
  nExamTitle: 'امتحان {name} غداً', nExamBody: 'راجع خطتك ونم قبل منتصف الليل.',
  nFocusTitle: 'اكتملت جلسة التركيز', nFocusBody: '{task} · +50 XP',
  badgesN: ['سلسلة 7 أيام', 'مبكّر', '50 ساعة', 'جاهز للامتحان'],
  cmdTitle: 'ماذا لديك قادماً؟', cmdPh: 'مثلاً: امتحان فيزياء يوم الخميس', tryThis: 'جرّب',
  quick: ['امتحان فيزياء يوم الخميس', 'مهمة: تقرير المختبر قبل الأربعاء', 'نادي رياضي 3 مرات أسبوعياً'],
  building: 'نظّم يبني خطتك…', built: 'بُنيت من جملة واحدة', builtCount: '5 عناصر',
  addAll: 'أضف الكل إلى خطتي',
  gen: [
    ['تلخيص الفصول 4–6', 'اليوم · 16:00 · 40 دقيقة', 'task'],
    ['جلسة حل مسائل 1', 'الثلاثاء · 11:00 · 50 دقيقة', 'focus'],
    ['امتحان سابق 2024', 'الأربعاء · 14:00 · 90 دقيقة', 'task'],
    ['النوم قبل منتصف الليل', 'حتى الخميس', 'habit'],
    ['امتحان الفيزياء', 'الخميس · 09:00 · قاعة C', 'class'],
  ],
  toastTask: 'مهمة منجزة · +20 XP', toastHabit: 'عادة محققة · +10 XP', toastFocus: 'اكتملت الجلسة · +50 XP', toastAdded: 'بُنيت خطة المراجعة · +30 XP',
  tabToday: 'اليوم', tabPlan: 'الخطة', tabFocus: 'التركيز', tabMe: 'التقدم',
  dow: ['ح', 'ن', 'ث', 'ر', 'خ', 'ج', 'س'],
  min: 'دقيقة', of: 'من', done: 'منجز', xpTo: 'XP للمستوى', streakSuffix: ' يوم',
  profile: 'الملف الشخصي', editProfile: 'تعديل الملف', saveProfile: 'حفظ', fName: 'الاسم', fUni: 'الجامعة', fMajor: 'التخصص', fYear: 'السنة',
  defaultName: 'أحمد', defaultUni: 'جامعة السلطان قابوس', defaultMajor: 'علوم الحاسب', defaultYear: 'السنة الثانية',
  dayStreak: 'أيام متتالية', yourPlan: 'باقتك', manage: 'إدارة', upgrade: 'ترقية', memberSince: 'تدرس مع نظّم منذ مايو',
  settings: 'الإعدادات', sGeneral: 'عام', sControls: 'التحكم', sAccount: 'الخصوصية والحساب', version: 'نظّم 1.0.0',
  cHaptics: 'الاهتزاز', cHapticsSub: 'نقرة خفيفة عند إنجاز أي شيء',
  cRewards: 'المكافآت والنقاط', cRewardsSub: 'المستويات والسلاسل والنقاط',
  cAi: 'اقتراحات الذكاء', cAiSub: 'إظهار نصائح ذكاء نظّم في اليوم', cFocusLen: 'مدة التركيز الافتراضية',
  plans: 'الباقات', plansSub: 'كل شيء مجاني الآن — و«برو» في الطريق.', monthly: 'شهري', yearly: 'سنوي',
  csTitle: 'برو قادم قريباً', csBadge: 'قريباً',
  csSub: 'كل أجزاء نظِّم مجانية الآن. سيضيف «برو» مزايا متقدمة لمن يريد أكثر — وستكون أول من يعرف.',
  csFreeNow: 'كل المزايا مجانية حالياً', csWhat: 'ماذا سيضيف برو', csBack: 'واصل استخدام نظِّم مجاناً',
  tiers: {
    free: { name: 'مجاني', tag: 'خطوتك التالية كل يوم', per: 'دائماً',
      features: ['اليوم: ماذا تفعل الآن', 'المواد والمهام والتركيز المرتبط بها', 'المخطط الذكي لامتحانين نشطين', 'خطة الإنقاذ عند التأخر'] },
    plus: { name: 'Plus', tag: 'لفصل دراسي كامل', per: '',
      features: ['كل ميزات المجاني', 'امتحانات وخطط مذاكرة بلا حدود', 'كل ملاحظات التقدم', 'تذكيرات الامتحانات وخطة اليوم'] },
    pro: { name: 'Pro', tag: 'فصلك الدراسي على وضع تلقائي', per: '',
      features: ['كل ميزات Plus', 'مزامنة التقويم (قريباً)', 'مدرّب مذاكرة ذكي (قريباً)', 'دعم ذو أولوية'] },
  },
  perMonth: '/ شهرياً', perYear: '/ سنوياً', yearNote: '{m} شهرياً، تُدفع سنوياً', save: 'وفّر {n}%', bestValue: 'الأفضل قيمة',
  currentPlan: 'باقتك الحالية', choose: 'اختر {name}', switchFree: 'التحويل إلى المجاني',
  trialCta: 'ابدأ تجربة 7 أيام مجاناً',
  legal: 'مجاناً لمدة 7 أيام، ثم {p}. يتجدد الاشتراك تلقائياً ما لم يُلغَ قبل 24 ساعة على الأقل من نهاية الفترة الحالية. يمكنك الإدارة أو الإلغاء في الإعدادات › Apple ID › الاشتراكات.',
  restore: 'استعادة المشتريات', terms: 'شروط الاستخدام', privacyL: 'سياسة الخصوصية', support: 'الدعم',
  deleteAcc: 'حذف الحساب', delTitle: 'حذف حسابك؟',
  delBody: 'سيتم حذف حسابك وكل موادك وامتحاناتك وخططك وتقدمك نهائياً من خوادم نظّم ومن هذا الجهاز. لا يمكن التراجع عن ذلك.',
  cancel: 'إلغاء', delConfirm: 'حذف نهائي', toastDel: 'تم طلب حذف الحساب',
  exAdd: 'أضف امتحاناً', exNew: 'امتحان جديد', exSubject: 'المادة', exSubjectPh: 'مثلاً: الفيزياء', exDate: 'موعد الامتحان',
  exChapters: 'الفصول أو المواضيع', exChaptersPh: 'كل فصل في سطر، مثلاً:\nالفصل 4\nالفصل 5', exCreate: 'ابنِ خطة مراجعتي',
  exPreview: '{s} جلسة خلال {d} أيام: دراسة كل فصل، ثم مراجعته بعد يوم و3 أيام و7 أيام، ثم امتحان تجريبي في اليوم السابق.',
  exTooSoon: 'اختر موعداً بعد يوم واحد على الأقل.', exNeedsChapters: 'أضف فصلاً واحداً على الأقل.',
  exReady: 'جاهز', exLeft: '{c} متبقية', exDelete: 'حذف الامتحان', exDeleteConfirm: 'اضغط مرة أخرى للحذف',
  exNone: 'لا توجد امتحانات بعد. أضف امتحاناً ويخطط نظّم مراجعتك.', exHow: 'مراجعة متباعدة: كل فصل يعود بعد يوم و3 أيام و7 أيام. "صعب" يضيف مراجعة غداً، و"سهل" يلغي واحدة.',
  exChaptersH: 'الفصول', exChaptersN: '{c}', exPlanH: 'خطة المراجعة', exAll: 'كل الفصول', exDay: 'يوم الامتحان',
  // أربع صيغ لكل معدود: مفرد، مثنّى، جمع (3–10)، ثم تمييز منصوب (11+).
  // المثنى هنا بصيغة النصب/الجر («يومين» لا «يومان») لأنه يرد في الواجهة بعد حرف جر في الغالب الأعم:
  // «بعد يومين»، «خلال جلستين». وصيغة الرفع تبدو متكلّفة في هذه السياقات.
  units: {
    day: ['يوم', 'يومين', 'أيام', 'يوماً'], session: ['جلسة', 'جلستين', 'جلسات', 'جلسة'],
    chapter: ['فصل', 'فصلين', 'فصول', 'فصلاً'], task: ['مهمة', 'مهمتين', 'مهام', 'مهمة'],
    minute: ['دقيقة', 'دقيقتين', 'دقائق', 'دقيقة'], card: ['بطاقة', 'بطاقتين', 'بطاقات', 'بطاقة'],
    exam: ['امتحان', 'امتحانين', 'امتحانات', 'امتحاناً'],
  },
  // ── اختبار الاسترجاع ──
  rcTitle: 'اختبار ذاتي', rcSub: 'أثبت أنك تستطيع الاسترجاع', rcOpen: 'اختبر نفسك',
  rcEmpty: 'لا توجد بطاقات بعد. اكتب سؤالاً تتوقّعه في الامتحان، والإجابة بكلماتك أنت.',
  rcEmptyWhy: 'كتابة البطاقة مذاكرة في حد ذاتها. والإجابة عليها لاحقاً هي ما يحوّل أدلتك إلى رقم له معنى.',
  rcAdd: 'أضف بطاقة', rcQ: 'السؤال', rcQPh: 'مثلاً: ماذا تنصّ نظرية الحد المركزي؟',
  rcA: 'الإجابة', rcAPh: 'بكلماتك أنت — هذه هي الإجابة التي ستصحّح لنفسك عليها.',
  rcSave: 'احفظ البطاقة', rcChapter: 'الفصل', rcCards: '{c}', rcCardsNone: 'لا بطاقات',
  rcDue: '{n} مستحقة', rcAllCaught: 'لا شيء مستحق الآن. المراجعة القادمة {d}.',
  rcYourAnswer: 'اكتب إجابتك أولاً', rcYourAnswerPh: 'استرجعها قبل أن تنظر. الكتابة نفسها هي التمرين.',
  rcReveal: 'أظهر الإجابة', rcGradeQ: 'كم اقتربت؟',
  rcGrades: ['نسيت', 'تقريباً', 'أتقنت'],
  rcSelfNote: 'لم نجد تطابقاً لفظياً مع الإجابة. قيّم نفسك كما ترى — وإن اخترت «أتقنت» فستُسجّل دليلاً ذاتياً، وهو أقل وزناً من دليل مُثبَت.',
  rcDone: 'انتهى الاختبار الذاتي', rcScore: 'استرجعت {c} من {n}', rcBack: 'العودة للامتحان',
  rcDelete: 'حذف البطاقة', rcNext: 'البطاقة التالية', rcProgress: '{i} من {n}',
  // ── شرح اكتمال الدليل ──
  rdWhy: 'لماذا هذا الرقم؟', rdTitle: 'كيف يُقاس اكتمال الدليل', rdEvidence: 'الدليل',
  rdIntro: 'هذا الرقم يصف قوة الأدلة التي جمعتها عن استعدادك، وليس توقعاً لدرجتك. كل فصل يكسبه بثلاث طرق.',
  rdCoverage: 'الفصول المدروسة', rdEffort: 'دقائق التركيز', rdRecall: 'الاسترجاع المُثبَت',
  rdEffortVal: '{a} من {b} مخططة', rdRecallNone: 'لم تختبر نفسك بعد', rdRecallVal: 'استرجعت {n}%',
  rdCeiling: 'الضغط على «تم» وحده يحدّ الفصل عند {n}%. وقضاء الدقائق المخططة في جلسة تركيز يرفعه إلى {e}%. ولا يتجاوز ذلك إلا باختبار ذاتي — واختبار ذاتي يسوء يخفضه.',
  rdNow: 'الآن', rdMax: 'الحد الممكن بلا دليل جديد',
  evNext: 'الدليل التالي', evStart: 'ابدأ الآن', evStudy: 'ادرس {c}', evFocus: 'ركّز على {c}',
  evRecall: 'اختبر {c}', evMock: 'أدِّ الاختبار التجريبي', evReady: 'الدليل مكتمل',
  evDayDone: 'أنهيت جدول اليوم. وهذا أقوى دليل تالٍ إن أردت المتابعة.',
  evNoExam: 'أضف امتحانك القادم', evNoExamSub: 'مادة وتاريخ وأسماء فصولك — وبعدها يستطيع نظّم أن يقول لك ما تفعله أولاً.',
  evWhy: 'لماذا هذا الرقم؟',
  evBand: ['أدلة قليلة بعد — كل جلسة وبطاقة تضيف إليها', 'الأدلة تتراكم — واصل اختبار نفسك', 'أدلة قوية — حافظ عليها حتى الامتحان'],
  rdNextStudy: 'ادرس الفصل {c} — لم تعمل عليه بعد.',
  rdNextFocus: 'ركّز جلسة حقيقية على الفصل {c}. مُعلَّم كمنجز لكنه بالكاد دُرس.',
  rdNextRecall: 'اختبر نفسك في الفصل {c}. الاسترجاع هو الدليل الناقص.',
  rdNextMock: 'اجلس للامتحان التجريبي لتأكيدها.', rdNextReady: 'أنت جاهز. حافظ عليها بمراجعات قصيرة.',
  rdDecay: 'لم تلمسه منذ {n} يوماً — العمل الأقدم يُحتسب أقل قليلاً.',
  kLearn: 'دراسة', kReview: 'مراجعة', kMock: 'امتحان تجريبي', rateQ: 'ما مدى فهمك؟', rates: ['صعب', 'متوسط', 'سهل'],
  reviewsToday: 'مراجعة اليوم', onDay: 'الجدول · {d}', nothingDay: 'لا شيء مخطط. يوم فارغ.', startS: 'ابدأ', doneS: 'تم',
  dToday: 'اليوم', dTomorrow: 'غداً', dIn: 'بعد {c}', toastRated: 'تم الحفظ · +20 XP',
  wd: ['الأحد', 'الاثنين', 'الثلاثاء', 'الأربعاء', 'الخميس', 'الجمعة', 'السبت'], wdLong: ['الأحد', 'الاثنين', 'الثلاثاء', 'الأربعاء', 'الخميس', 'الجمعة', 'السبت'],
  months: ['يناير', 'فبراير', 'مارس', 'أبريل', 'مايو', 'يونيو', 'يوليو', 'أغسطس', 'سبتمبر', 'أكتوبر', 'نوفمبر', 'ديسمبر'],
  sampleExam: { subject: 'الرياضيات', chapters: ['النهايات', 'المشتقات', 'قاعدة السلسلة', 'التكامل'] },
  aiExam: { subject: 'الفيزياء', chapters: ['الفصل 4 · الحركة', 'الفصل 5 · القوى', 'الفصل 6 · الطاقة'] },
  seed: {
    subjects: ['الإحصاء', 'التفاضل والتكامل', 'الفيزياء'], examName: 'الإحصاء',
    chapters: ['الفصل الأول', 'الفصل الثاني', 'الفصل الثالث', 'الفصل الرابع'],
    tasks: ['أسئلة تدريبية على الفصل الثالث', 'تقرير مختبر الفيزياء', 'مسائل التفاضل 2'],
  },
  greetings: ['صباح الخير', 'مساء الخير', 'مساء الخير'], nextMove: 'خطوتك التالية', startSession: 'ابدأ الجلسة',
  rOverdue: 'متأخرة منذ {n} أيام', rOverdue1: 'متأخرة منذ أمس', rExamSoon: 'امتحان {exam} بعد {n} أيام', rExamTomorrow: 'امتحان {exam} غداً',
  rDueToday: 'مستحقة اليوم', rDueTomorrow: 'مستحقة غداً', rPlanned: 'جزء من خطة مذاكرتك',
  nextClear: 'أنجزت كل ما عليك اليوم.', nextClearSub: 'لا شيء مستحق الآن. استرح، أو تقدّم في امتحانك القادم.',
  nextAdd: 'أضف امتحانك الأول', nextAddSub: 'ونظّم يبني لك خطة المذاكرة.',
  overall: 'التقدم العام', todaySchedule: 'جدول اليوم', emptyToday: 'لا شيء في جدول اليوم.',
  load: 'العبء الدراسي', loadLevels: ['خفيف', 'متوسط', 'مرتفع'], loadSub: '{h} مخططة هذا الأسبوع', nextDeadline: 'الموعد القادم',
  kExam: 'امتحان', kTaskB: 'مهمة', kStudyB: 'مذاكرة', markDoneA: 'تحديد كمنجزة',
  tabSubjects: 'المواد', tabMore: 'المزيد', subjects: 'المواد الدراسية', target: 'الهدف {g}', addSubject: 'أضف مادة', newSubject: 'مادة جديدة',
  subjName: 'اسم المادة', subjNamePh: 'مثلاً: الإحصاء', targetGrade: 'الدرجة المستهدفة', colour: 'اللون', icon: 'الأيقونة', create: 'إنشاء',
  progressL: 'التقدم', nextTask: 'المهمة الدراسية التالية', tasksL: 'المهام', pendingN: '{n} متبقية', examsL: 'الامتحانات', upcomingN: '{n} قادمة',
  studyL: 'المذاكرة', sessionsMonth: '{n} جلسات هذا الشهر', addTask: 'أضف مهمة', taskTitlePh: 'مثلاً: أسئلة الفصل الثالث',
  tasksTitle: 'المهام', tkOpenN: 'المفتوحة: {n}', tkSmart: 'ترتيب ذكي', tkByDue: 'حسب الموعد', tkShowDone: 'إظهار المنجزة', tkHideDone: 'إخفاء المنجزة',
  tkGroups: { overdue: 'تجاوزت موعدها', today: 'اليوم', soon: 'هذا الأسبوع', later: 'لاحقاً', done: 'منجزة' },
  tkWhy: { overdue: 'تجاوزت موعدها', dueToday: 'مستحقة اليوم', plannedToday: 'مخطط لها اليوم', examSoon: 'امتحانها قريب', highPriority: 'وسمتها مهمة', dueTomorrow: 'مستحقة غداً', quickWin: 'إنجاز سريع', dueLater: '', done: '' },
  tkSmartWhy: 'ما تجاوز موعده أولاً، ثم اليوم، ثم هذا الأسبوع. وفي كل قسم يرتفع ما وسمته مهماً، وما موعده أقرب، وما لمادته امتحان قريب.',
  tkEmptyT: 'لا مهام بعد', tkEmptyS: 'اكتبها في سطر واحد — «مقال الإحصاء غداً 45 د» — ونظّم يكمل الباقي.',
  tkQuickPh: 'مثلاً: مقال الإحصاء غداً 45 د', tkUnderstood: 'فهمت', tkTitleL: 'العنوان', tkPriority: 'الأهمية',
  tkPriorities: ['منخفضة', 'عادية', 'عالية'], tkNotes: 'ملاحظات', tkNotesPh: 'صفحات، روابط، ما المطلوب تسليمه…', tkDueDate: 'الموعد النهائي',
  tkEdit: 'تعديل المهمة', tkSave: 'احفظ التعديلات', tkSavedT: 'حُفظت المهمة', tkMoveTomorrow: 'أجّلها للغد',
  tkMoveNote: 'ينقل اليوم الذي تعمل فيها. الموعد النهائي يبقى {d}.', tkMovedT: 'نُقلت إلى الغد. ما زال موعدها {d}.',
  tkMarkDone: 'تمّت', tkMarkOpen: 'لم تتم بعد', tkDelete: 'حذف المهمة', tkDeleteConfirm: 'اضغط مرة أخرى للحذف',
  tkInvalid: 'تعذّر الحفظ. تحقّق من العنوان والتاريخ.', tkPlannedFor: 'ستعمل عليها {d}', tkPlusMin: '+5 د', tkMinusMin: '−5 د',
  tkDayEarlier: 'يوم أبكر', tkDayLater: 'يوم أبعد', tkAll: 'كل المهام',
  due: 'الموعد', estimate: 'المدة', noSubjects: 'أضف موادك لترى فصلك الدراسي في مكان واحد.', deleteSubject: 'حذف المادة',
  noTasks: 'لا مهام بعد.', examFor: 'المادة', more: 'المزيد', upcomingExams: 'الامتحانات القادمة', progressMenu: 'التقدم',
  inDaysShort: 'بعد {n} أيام', allClear: 'لا شيء متأخر',
  limitExams: 'المجاني يغطي امتحانين نشطين. Plus يخطط لكل امتحاناتك.',
  freeFocus: 'تركيز حر',
  studyTimeQ: 'متى تذاكر عادةً؟', studyTimeSub: 'خطة يومك وتذكيرك يتبعانه.', studyTimes: ['صباحاً', 'ظهراً', 'مساءً', 'ليلاً'],
  streakA: '{n} أيام مذاكرة متتالية', clTitle: 'البداية', clProgress: '{d} من {t}', clHide: 'إخفاء',
  clSteps: { semester: 'جهّز فصلك الدراسي', focus: 'أنهِ أول جلسة تركيز', rate: 'قيّم جلسة أو أنجز مهمة', reminders: 'فعّل تذكيرك اليومي', account: 'احفظ نسخة بحساب مجاني' },
  recapTitle: 'أسبوعك الماضي', recapBody: '{m} تركيز · {d} أيام مذاكرة · {s} جلسات منجزة', recapNext: 'هذا الأسبوع: {m} مخططة.', recapCta: 'اعرض هذا الأسبوع',
  remAskT: 'تريد تذكيراً غداً؟', remAskB: 'تذكير واحد الساعة {t} بخطوتك التالية. غيّره أو أطفئه متى شئت.', remAskYes: 'ذكّرني', remDailyAt: 'يومياً الساعة {t}',
  toastReady: 'دليل {exam} {a}% ← {b}%',
  toastFocusAway: 'كان التطبيق في الخلفية طوال الجلسة، فلم تُحتسب دقائق تركيز.', nDailyBody: 'التالي: {t}', nStreakTitle: '{n} أيام مذاكرة متتالية', nStreakBody: 'جلسة 10 دقائق اليوم تحافظ عليها.',
  examToday: 'امتحان اليوم', nowL: 'الآن', dayProgress: 'أُنجز {d} من {t} · متبقٍ {m}', dayDone: 'أنجزت كل شيء لليوم',
  weekAhead: 'الأسبوع القادم بالساعات', weekClear: 'لا شيء مخطط في الأيام السبعة القادمة.',
  glanceSemester: 'اكتمال الدليل', glanceNoExam: 'المهام المنجزة', glanceWeek: 'المخطط القادم', glanceExam: 'الامتحان القادم', glanceNone: 'لا يوجد', smartPlan: 'خطة ذكية',
  emptyTodayT: 'لا شيء مخطط اليوم', emptyTodayS: 'أضف مهمة، أو خطط لامتحان ودع نظّم يملأ أيامك.',
  secAccount: 'الحساب', secStudy: 'الدراسة', secApp: 'التطبيق', subjExam: 'امتحان {d}', subjTasks: '{c} مفتوحة', subjClear: 'لا شيء مستحق',
  acTitle: 'الحساب', acSub: 'زامن فصلك الدراسي واحفظ نسخة منه', acSignIn: 'تسجيل الدخول', acCreate: 'إنشاء حساب',
  acBenefits: ['فصلك الدراسي على كل أجهزتك', 'نسخة محفوظة إذا فقدت هاتفك', 'يعمل دون إنترنت ويزامن عند عودتك'],
  acEmail: 'البريد الإلكتروني', acPassword: 'كلمة المرور (8 أحرف على الأقل)', acToCreate: 'جديد هنا؟ أنشئ حساباً', acToSignIn: 'لديك حساب؟ سجّل الدخول',
  acConfirm: 'افتح بريدك وأكّد عنوانك، ثم سجّل الدخول هنا.', acLocalNote: 'بدون حساب، تبقى بياناتك على هذا الجهاز فقط.',
  acErr: { invalid: 'البريد أو كلمة المرور غير صحيحة.', unconfirmed: 'أكّد بريدك أولاً (تحقق من صندوق الوارد).', weak: 'استخدم 8 أحرف على الأقل.', exists: 'يوجد حساب بهذا البريد. سجّل الدخول بدلاً من ذلك.', network: 'لا يوجد اتصال. حاول مجدداً.', unavailable: 'المزامنة غير مفعّلة في هذه النسخة.', unknown: 'حدث خطأ ما. حاول مجدداً.' },
  acSynced: 'تمت المزامنة {t}', acSyncing: 'جارٍ المزامنة…', acSyncError: 'تعذّرت المزامنة. تغييراتك محفوظة على هذا الجهاز.', acNever: 'لم تتم المزامنة بعد',
  acSyncNow: 'زامن الآن', acSignOut: 'تسجيل الخروج', acSignedIn: 'مسجّل باسم', acJustNow: 'الآن', acMinAgo: 'قبل {n} دقيقة',
  obHaveAccount: 'لدي حساب بالفعل', delLocalTitle: 'مسح البيانات من هذا الجهاز؟',
  delLocalBody: 'سيتم مسح موادك وامتحاناتك وخططك وتقدمك من هذا الجهاز. لا يمكن التراجع عن ذلك.', toastDelFail: 'تعذّر الحذف. تحقق من الاتصال.',
  xDaysLeft: 'متبقٍ {c}', xDayLeft: 'غداً', xToday: 'اليوم', xOver: 'انتهى', xReadiness: 'اكتمال الدليل',
  xStatus: { onTrack: 'على المسار', behind: 'متأخر قليلاً', atRisk: 'يحتاج تركيزاً الآن', ready: 'جاهز', over: 'انتهى الامتحان', unknown: 'التاريخ يحتاج مراجعة' },
  xStatusSub: { onTrack: 'استمر على الخطة.', behind: 'فاتتك {n} جلسات. جلسة اليوم تعيدك للمسار.', atRisk: 'أيام قليلة متبقية. أنجز الجلسة التالية والاختبار التجريبي.', ready: 'مراجعات خفيفة وراحة قبل الامتحان.', over: 'كيف كان؟ عملك محسوب في تقدم فصلك.', unknown: 'تاريخ هذا الامتحان غير مقروء، فلا شيء مجدول له. أعد تعيين التاريخ.' },
  xRemaining: 'متبقٍ: {s} · {t}', xPerDay: 'حوالي {m} يومياً', xNextBtn: 'ابدأ التالي: {t}', xTopics: 'المواضيع', xPlan: 'خطة المذاكرة',
  xTopicState: { notStarted: 'لم يبدأ', learning: 'قيد التقدم', solid: 'متمكن', weak: 'يحتاج عملاً' },
  xPhase: { learn: 'المرحلة 1 من 3 · القراءة الأولى', review: 'المرحلة 2 من 3 · المراجعات', final: 'المرحلة 3 من 3 · الاستعداد النهائي' },
  xMock: 'الاختبار التجريبي {d}: أفضل مؤشر على أدائك في الامتحان.', xAdjust: 'غيّر الموعد أو الفصول', xDoneN: 'أُنجز {n}',
  xFocusOn: 'ركّز هنا: {t}',
  obTag: 'من الفوضى الأكاديمية إلى خطة واضحة.', obStart: 'ابدأ', obSample: 'استكشف بفصل دراسي تجريبي',
  obStep: 'الخطوة {n} من 3', obAboutT: 'أين تدرس؟', obAboutS: 'لتناسب الخطط فصلك الدراسي. يمكنك تخطي أي حقل.',
  obSubjOne: 'ما المادة؟', obSubjOneS: 'المادة التي لك فيها امتحان قريب. البقية تُضاف لاحقاً.',
  obDateT: 'متى الامتحان؟', obDateS: 'اختر التاريخ الحقيقي — الخطة كلها تُبنى منه إلى الخلف.',
  obChapT: 'ما فصولها؟', obChapS: 'فصل في كل سطر، بكلماتك. «فترات الثقة» أنفع بكثير من «الفصل 3» حين يأتيك الدليل التالي.',
  obChapPh: 'الاحتمال\nتوزيعات المعاينة\nفترات الثقة',
  obGo: 'أرِني ما أفعله أولاً', obLater: 'اسمك وجامعتك يمكن أن ينتظرا — أضفهما وقت ما شئت من الملف الشخصي.',
  obSubjT: 'موادك هذا الفصل', obSubjS: 'أضف كل مقرر والدرجة التي تطمح لها.', obSubjPh: 'مثلاً: الإحصاء',
  obExamT: 'امتحانك القادم', obExamS: 'يحوّله نظّم إلى خطة مذاكرة يوماً بيوم.', obWhich: 'المادة', obWhen: 'الموعد', obChapters: 'الفصول',
  obBuild: 'لنبنِ فصلك الدراسي', obNext: 'التالي', obSkip: 'تخطي', obNoExam: 'لا يوجد امتحان قريب بعد', noName: 'طالب',
  qaTitle: 'إضافة', qaTask: 'مهمة أو واجب', qaTaskSub: 'واجب، تقرير مختبر، قراءة', qaExam: 'امتحان',
  qaExamSub: 'نظّم يبني خطة المذاكرة', qaSubject: 'مادة', qaSubjectSub: 'مقرر في هذا الفصل',
  prSemester: 'اكتمال الدليل', prConsistency: 'الانتظام في المذاكرة', prActive: '{n} من 7 أيام', prTasks: 'المهام المنجزة',
  sbReady: 'دليل', sbDone: 'منجز', prWorkDone: 'أُنجز {n}% من العمل المخطط',
  toastPurchasePending: 'جارٍ التأكيد مع المتجر…', toastPurchaseOff: 'الاشتراكات غير متاحة بعد.',
  toastPurchaseCancelled: 'أُلغيت عملية الشراء.', toastPurchaseFailed: 'لم يتمكّن المتجر من إتمام العملية.',
  toastRestored: 'استُعيدت مشترياتك.', toastRestoreNone: 'لا توجد عملية شراء لهذا الحساب.',
  payOff: 'نظِّم مجاني بينما تُجهَّز الاشتراكات. كل ما تراه مشمول.',
  payRestore: 'استعادة المشتريات',
  prReadySub: 'عبر الامتحانات القادمة', prNoExams: 'أضف امتحاناً لتبدأ جمع الأدلة', prTasksN: '{d} من {t}', prWeek: 'ركّزت فعلياً', prSubjects: 'تقدم المواد', prReady: 'الدليل {n}%', prInsights: 'ملاحظات',
  prWeekBars: 'التركيز هذا الأسبوع', prActiveDays: 'أيام نشطة', prNoSubjects: 'أضف موادك لترى تقدم كل مادة.',
  iAtRisk: 'امتحان {exam} بعد {n} أيام ودليلك عند {r}%. جلسة اليوم هي الأهم.', iAtRisk1: 'امتحان {exam} غداً ودليلك عند {r}%. اختبر نفسك اليوم.',
  iBehind: 'تأخرت {n} مهام. خطة الإنقاذ تعيد ترتيب أسبوعك في دقيقة.', iUp: 'دليل {exam} ارتفع {n} نقطة هذا الأسبوع.',
  iHeavier: 'الأسبوع القادم أثقل: {n} مخطط مقابل {c} هذا الأسبوع. البدء مبكراً يبقيه هادئاً.', iConsistency: 'ذاكرت في {n} من آخر 7 أيام.',
  iStart: 'أنهِ جلسة واحدة اليوم وسيبدأ تقدمك من هنا.',
  rescueEyebrow: 'ترتيب اليوم', rescueTitle: 'وقت اليوم محدود.', rescueSub: 'لذلك سنرتّب ما يستحق وقتك أولاً.',
  trNow: 'الآن', trLater: 'لاحقاً', trNowSub: 'ثلاثة أشياء، وتتّسع في يوم عادي بالنسبة لك.',
  trWhy: { examSoon: 'الامتحان قريب', evidenceGap: 'أضعف دليل', overdue: 'تجاوز تاريخه', dueToday: 'مستحق اليوم' },
  trRebuild: 'أو أعد ترتيب الأسبوع كله', trNothing: 'لا شيء يزاحم وقت اليوم.',
  trCapacity: 'المطلوب اليوم {a} · ويومك المعتاد {b}',
  rOverdueN: '{u} متأخرة', rExamsN: '{u} قادمة', rWorkN: 'عمل هذا الأسبوع', capacityL: 'في اليوم العادي أستطيع المذاكرة',
  buildRescue: 'ابنِ خطة الإنقاذ', applyRescue: 'طبّق الخطة', rescueNote: 'المواعيد النهائية لا تتغير، يتغير فقط وقت إنجاز العمل.',
  rescueOk: 'الخطة تناسب وقتك. سيتم نقل {n} عناصر دون أن يضيع شيء.', rescueOnTrack: 'أنت على المسار. لا شيء يحتاج إلى نقل.',
  rescueTight: 'بعض الأيام ما زالت مزدحمة. ابدأ بالعناصر المعلّمة، أو اطلب تمديداً.', rescueDropped: 'حُذفت {n} مراجعات إضافية، والمراجعات اللاحقة تغطيها.',
  movedFrom: 'من {d}', tightL: 'زائد', toastRescue: 'أُعيد بناء خطتك. خطوة بخطوة.', rescueMenu: 'ترتيب اليوم',
  behindTitle: 'اليوم مُحمَّل أكثر من طاقته', behindOverdue: '{n} تجاوزت تاريخها.', behindLoad: 'المطلوب اليوم أكثر مما يحمله يوم عادي.', rebuild: 'أعد الترتيب',
  sessionComplete: 'انتهت الجلسة', howWent: 'كيف كانت؟ هذا يحدّث دليل هذا الامتحان.', taskDoneQ: 'هل أنهيت المهمة؟',
  yesDone: 'نعم، أنهيتها', notYet: 'ليس بعد', focusMin: '{n} دقيقة تركيز', rHard: 'صعبة', rOk: 'جيدة', rEasy: 'سهلة',
  plEyebrow: 'المخطط الذكي', plTitle: 'أخبر نظّم بما تحتاجه.', plSub: 'امتحاناتك ووقتك في خطة واحدة.',
  plPh: 'مثلاً: عندي اختبار Statistics بعد 6 أيام ولم أبدأ', plRun: 'خطّط',
  plTry: ['عندي اختبار Statistics بعد 6 أيام ولم أبدأ', 'نهائي Calculus الأسبوع القادم، 5 فصول', 'كويز Physics يوم الخميس'],
  plDays: 'خطة مذاكرة لـ {n} أيام', plWhy: 'لماذا هذه الخطة', plApply: 'أضف إلى خطتي', plReplaces: 'تستبدل خطة {s} الحالية.',
  plNeed: 'اذكر المادة وموعد الامتحان، مثلاً: «امتحان فيزياء بعد 5 أيام».', plChapters: 'الفصول', plWhen: 'الامتحان',
  plNewSubject: 'مادة جديدة: {s}', plChapterN: 'الفصل {n}', plR1: 'تبدأ اليوم، قبل الامتحان بـ {n} أيام.',
  plR2: 'كل فصل يعود بعد 1 و3 و7 أيام، وهو التباعد الذي يثبّت المعلومة.', plR3: 'اختبار تجريبي في اليوم السابق.',
  plR4: 'حوالي {m} يومياً، ضمن وقتك ({c}).', plR4over: 'حوالي {m} يومياً، أكثر من وقتك المعتاد ({c}). ابدأ اليوم.',
  plR5: 'وُزّعت حول {n} عناصر موجودة في جدولك.', plDone: 'أُضيفت الخطة. أول جلسة في صفحة اليوم.',
  toastPlan: 'تم تفعيل {name} (تجريبي، بدون دفع)', toastFree: 'تم التحويل إلى المجاني', toastSaved: 'تم حفظ الملف', aBack: 'رجوع',
  aNew: 'خطة جديدة', aReset: 'إعادة المؤقت', aPlay: 'تشغيل أو إيقاف التركيز', aFinish: 'إنهاء الجلسة', aClose: 'إغلاق',
  rcYours: 'إجابتك',
  rcCheckT: 'إجابتك قد تحتاج مراجعة',
  rcOverride: 'إجابتي كانت صحيحة',
  rcOverrideNote: 'نحترم تقديرك وتُسجَّل «أتقنت». ولأن الصياغة لم تتطابق، تُحسب دليلاً ذاتياً.',
  rcGradeHint: ['لم تسترجعها — تعود البطاقة غداً', 'استرجاع جزئي — تعود أسرع من بطاقة أتقنتها', 'استرجعتها — تطول المدة قبل عودتها'],
  rcRevealHint: 'اكتب شيئاً أولاً — المحاولة نفسها هي المذاكرة',
  rcEmptyT: 'لا بطاقات بعد', rcDeleteConfirm: 'اضغط مرة أخرى لحذف البطاقة',
  subjEmptyT: 'ابدأ بمادة واحدة', subjEmptyS: 'مادة واحدة وامتحانها القادم يكفيان ليخطط نظّم أيامك.',
  offT: 'أنت غير متصل', offS: 'كل ما تفعله محفوظ على جهازك.',
  errT: 'واجهت هذه الشاشة مشكلة', errS: 'خطتك محفوظة على جهازك. حاول مرة أخرى — وإن تكرر ذلك راسلنا على support@nazzim.app.', errRetry: 'حاول مرة أخرى',
};

export const COPY: Record<Lang, Copy> = { en, ar };

export const kindLabel = (L: Copy, k: Kind) => ({ class: L.kClass, task: L.kTask, focus: L.kFocus, habit: L.kHabit })[k];

export type Unit = keyof Copy['units'];

/**
 * A number with its noun, agreeing properly in both languages.
 *
 * English takes two forms. Arabic takes four, and getting this wrong is the clearest sign an app was
 * translated rather than written: "1 أيام" and "11 أيام" are both wrong, and both were everywhere.
 *   1  → مفرد بلا عدد        يوم
 *   2  → مثنّى بلا عدد        يومان
 *   3–10 → العدد + جمع قلّة   ٣ أيام
 *   11+ → العدد + تمييز مفرد منصوب   ١١ يوماً
 * The 3–10 and 11+ rules repeat for every hundred, so 103 and 111 behave like 3 and 11.
 */
export function counted(n: number, unit: Unit, L: Copy, ar: boolean): string {
  const noun = unitOf(n, unit, L, ar);
  // Arabic drops the numeral for one and two: "يوم", "يومين" — writing "1 يوم" marks the app as translated.
  return ar && Math.abs(n) <= 2 ? noun : `${n} ${noun}`;
}

/** Just the noun in the form that agrees with `n`, for layouts that print the number separately. */
export function unitOf(n: number, unit: Unit, L: Copy, ar: boolean): string {
  const f = L.units[unit];
  const a = Math.abs(n);
  if (!ar) return f[a === 1 ? 0 : 1];
  if (a === 1) return f[0];
  if (a === 2) return f[1];
  const within = a % 100;
  return within >= 3 && within <= 10 ? f[2] : f[3];
}
