export type Lang = 'en' | 'ar';
export type Kind = 'class' | 'task' | 'focus' | 'habit';

const en = {
  appName: 'Nazzim', splashTag: 'From academic chaos to a clear plan.',
  splashParts: ['Plan', 'Focus', 'Exams', 'Progress'], madeIn: 'Made in Oman', aSkip: 'Skip',
  dateLine: 'MONDAY · 11 MAY', greet: 'Morning, ', now: 'NOW', nowRange: '10:30 – 11:15',
  nowTitle: 'Review Chapter 3 — Calculus', nowMeta: 'Maths · 35 min left · exam in 3 days',
  startFocus: 'Start focus', markDone: 'Done',
  aiTag: 'NAZZIM AI · BETA', aiLine: 'Your exam is in 3 days. I moved your hardest block to 10:30 — the hour you focus best.',
  stream: 'Today', kClass: 'Class', kTask: 'Task', kFocus: 'Focus', kHabit: 'Habit',
  plan: 'Plan', planSub: 'Calendar, tasks and exams — one view', exams: 'EXAMS', daysLeft: 'days left',
  planExamCta: 'Plan a new exam in one sentence', weekTasks: 'THIS WEEK',
  focus: 'Focus', focusOn: 'FOCUSING ON', ready: 'READY', inFocus: 'IN FOCUS', paused: 'PAUSED',
  sound: 'Sound', sounds: ['Off', 'Rain', 'Café'], lock: 'Silence other apps', lockSub: 'Blocks social apps while you focus',
  me: 'Progress', meSub: 'How your semester is going', level: 'LEVEL', rank: 'Focused scholar',
  stFocus: 'Focus hours', stDone: 'Tasks done', stTrend: 'Vs last week',
  week: 'This week', weekSub: 'Focus minutes', habits: 'Habits', habitsHint: 'Tap a day',
  language: 'Language', langValue: 'English', proValue: '7 days free',
  appearance: 'Appearance', appearances: ['System', 'Light', 'Dark'],
  accentColor: 'App colour', accentNames: ['Blue', 'Pink', 'Violet', 'Teal'],
  reminders: 'Reminders', remindersSub: 'Habits, exams and focus sessions',
  remHabits: 'Daily plan reminder', remExams: 'Exam countdown', remExamsSub: 'The evening before, at 19:00',
  remFocus: 'Focus session ends', remFocusSub: 'Even when Nazzim is closed',
  remDenied: 'Notifications are off for Nazzim. Turn them on in Settings › Nazzim › Notifications.',
  remWeb: 'Reminders work in the iPhone and iPad app.',
  nHabitTitle: 'Your next move is ready', nHabitBody: 'Open Nazzim to see what to study now.',
  nExamTitle: '{name} exam tomorrow', nExamBody: 'Look over your plan and sleep before midnight.',
  nFocusTitle: 'Focus session complete', nFocusBody: '{task} · +50 XP',
  badgesN: ['7-day streak', 'Early bird', '50h focus', 'Exam ready'],
  cmdTitle: 'What’s coming up?', cmdPh: 'e.g. Physics exam on Thursday', tryThis: 'TRY',
  quick: ['Physics exam on Thursday', 'Add task: lab report by Wednesday', 'Gym 3 times a week'],
  building: 'Nazzim is building your plan…', built: 'BUILT FROM ONE SENTENCE', builtCount: '5 items',
  addAll: 'Add all to my plan',
  gen: [
    ['Summarise chapters 4–6', 'Today · 16:00 · 40 min', 'task'],
    ['Problem session 1', 'Tue · 11:00 · 50 min', 'focus'],
    ['Past paper 2024', 'Wed · 14:00 · 90 min', 'task'],
    ['Sleep before midnight', 'Until Thursday', 'habit'],
    ['Physics exam', 'Thu · 09:00 · Hall C', 'class'],
  ] as [string, string, Kind][],
  toastTask: 'Task done · +20 XP', toastHabit: 'Habit kept · +10 XP', toastFocus: 'Session complete · +50 XP', toastAdded: 'Revision plan built · +30 XP',
  tabToday: 'Today', tabPlan: 'Plan', tabFocus: 'Focus', tabMe: 'Progress',
  dow: ['S', 'M', 'T', 'W', 'T', 'F', 'S'],
  min: 'min', of: 'of', done: 'done', xpTo: 'XP to level', streakSuffix: 'd',
  profile: 'Profile', editProfile: 'Edit profile', saveProfile: 'Save', fName: 'Name', fUni: 'University', fMajor: 'Major', fYear: 'Year',
  defaultName: 'Ahmed', defaultUni: 'Sultan Qaboos University', defaultMajor: 'Computer Science', defaultYear: 'Year 2',
  dayStreak: 'Day streak', yourPlan: 'YOUR PLAN', manage: 'Manage', upgrade: 'Upgrade', memberSince: 'Studying with Nazzim since May',
  settings: 'Settings', sGeneral: 'GENERAL', sControls: 'CONTROLS', sAccount: 'PRIVACY & ACCOUNT', version: 'Nazzim 1.0.0',
  cHaptics: 'Haptics', cHapticsSub: 'A light tap when you complete something',
  cRewards: 'Rewards & XP', cRewardsSub: 'Levels, streaks and points',
  cAi: 'AI suggestions', cAiSub: 'Show Nazzim AI tips on Today', cFocusLen: 'Default focus length',
  plans: 'Plans', plansSub: 'Start free. Upgrade when your semester gets busy.', monthly: 'Monthly', yearly: 'Yearly',
  tiers: {
    free: { name: 'Free', tag: 'Your next move, every day', per: 'forever',
      features: ['Today: what to do right now', 'Subjects, tasks and focus linked to them', 'Smart Planner for 2 active exams', 'Rescue Mode when you fall behind'] },
    plus: { name: 'Plus', tag: 'For a full semester', per: '',
      features: ['Everything in Free', 'Unlimited exams and study plans', 'All progress insights', 'Exam and daily plan reminders'] },
    pro: { name: 'Pro', tag: 'Your semester on autopilot', per: '',
      features: ['Everything in Plus', 'Calendar sync (coming soon)', 'AI study coach (coming soon)', 'Priority support'] },
  },
  perMonth: '/ month', perYear: '/ year', yearNote: '{m} / month, billed yearly', save: 'Save {n}%', bestValue: 'Best value',
  currentPlan: 'Current plan', choose: 'Choose {name}', switchFree: 'Switch to Free',
  trialCta: 'Start 7-day free trial',
  legal: 'Free for 7 days, then {p}. Renews automatically unless cancelled at least 24 hours before the end of the current period. Manage or cancel anytime in Settings › Apple ID › Subscriptions.',
  restore: 'Restore purchases', terms: 'Terms of Use', privacyL: 'Privacy Policy', support: 'Support',
  deleteAcc: 'Delete account', delTitle: 'Delete your account?',
  delBody: 'This permanently erases your account and all its subjects, exams, plans and progress from Nazzim’s servers and this device. This can’t be undone.',
  cancel: 'Cancel', delConfirm: 'Delete permanently', toastDel: 'Account deletion requested',
  exAdd: 'Add exam', exNew: 'New exam', exSubject: 'Subject', exSubjectPh: 'e.g. Physics', exDate: 'Exam date',
  exChapters: 'Chapters or topics', exChaptersPh: 'One per line, e.g.\nChapter 4\nChapter 5', exCreate: 'Build my revision plan',
  exPreview: '{s} sessions over {d} days: study each chapter, review it after 1, 3 and 7 days, then a mock test the day before.',
  exTooSoon: 'Pick a date at least one day away.', exNeedsChapters: 'Add at least one chapter.',
  exReady: 'READY', exLeft: '{n} left', exDelete: 'Delete exam', exDeleteConfirm: 'Tap again to delete',
  exNone: 'No exams yet. Add one and Nazzim plans your revision.', exHow: 'Spaced review: each chapter comes back after 1, 3 and 7 days. Hard adds a review tomorrow; Easy skips one.',
  exChaptersH: 'CHAPTERS', exChaptersN: '{n} chapters', exPlanH: 'REVISION PLAN', exAll: 'All chapters', exDay: 'Exam day',
  kLearn: 'Study', kReview: 'Review', kMock: 'Mock test', rateQ: 'How well do you know it?', rates: ['Hard', 'OK', 'Easy'],
  reviewsToday: 'REVISION TODAY', onDay: 'SCHEDULE · {d}', nothingDay: 'Nothing planned. A free day.', startS: 'Start', doneS: 'Done',
  dToday: 'today', dTomorrow: 'tomorrow', dIn: 'in {n} days', toastRated: 'Saved · +20 XP',
  wd: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'], wdLong: ['SUNDAY', 'MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY'],
  months: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
  sampleExam: { subject: 'Mathematics', chapters: ['Limits', 'Derivatives', 'Chain rule', 'Integrals'] },
  aiExam: { subject: 'Physics', chapters: ['Chapter 4 · Motion', 'Chapter 5 · Forces', 'Chapter 6 · Energy'] },
  seed: {
    subjects: ['Statistics', 'Calculus', 'Physics'], examName: 'Statistics',
    chapters: ['Chapter 1', 'Chapter 2', 'Chapter 3', 'Chapter 4'],
    tasks: ['Chapter 3 practice questions', 'Physics lab report', 'Calculus problem set 2'],
  },
  greetings: ['Good morning', 'Good afternoon', 'Good evening'], nextMove: 'YOUR NEXT MOVE', startSession: 'Start session',
  rOverdue: 'Overdue by {n} days', rOverdue1: 'Overdue since yesterday', rExamSoon: '{exam} exam in {n} days', rExamTomorrow: '{exam} exam tomorrow',
  rDueToday: 'Due today', rDueTomorrow: 'Due tomorrow', rPlanned: 'Part of your study plan',
  nextClear: 'You’re on track for today.', nextClearSub: 'Nothing else is due. Rest, or get ahead on your next exam.',
  nextAdd: 'Add your first exam', nextAddSub: 'NAZZIM builds the study plan for you.',
  overall: 'Semester progress', todaySchedule: 'Today’s schedule', emptyToday: 'Nothing scheduled today.',
  load: 'Academic load', loadLevels: ['Light', 'Moderate', 'Heavy'], loadSub: '{h} planned this week', nextDeadline: 'Next deadline',
  kExam: 'Exam', kTaskB: 'Task', kStudyB: 'Study', markDoneA: 'Mark as done',
  tabSubjects: 'Subjects', tabMore: 'More', subjects: 'Subjects', target: 'Target {g}', addSubject: 'Add subject', newSubject: 'New subject',
  subjName: 'Name', subjNamePh: 'e.g. Statistics', targetGrade: 'Target grade', colour: 'Colour', icon: 'Icon', create: 'Create',
  progressL: 'Progress', nextTask: 'Next study task', tasksL: 'Tasks', pendingN: '{n} pending', examsL: 'Exams', upcomingN: '{n} upcoming',
  studyL: 'Study', sessionsMonth: '{n} sessions this month', addTask: 'Add task', taskTitlePh: 'e.g. Chapter 3 practice questions',
  due: 'Due', estimate: 'Time', noSubjects: 'Add your subjects to see your semester in one place.', deleteSubject: 'Delete subject',
  noTasks: 'No tasks yet.', examFor: 'Subject', more: 'More', upcomingExams: 'Upcoming exams', progressMenu: 'Progress',
  inDaysShort: '{n} days left', allClear: 'All clear',
  // Rescue Mode
  limitExams: 'Free covers 2 active exams. Plus plans every exam.',
  freeFocus: 'Free focus',
  examToday: 'Exam today', nowL: 'NOW', dayProgress: '{d} of {t} done · {m} left', dayDone: 'Everything for today is done',
  glanceSemester: 'Semester', glanceWeek: 'This week', glanceExam: 'Next exam', glanceNone: 'None yet', smartPlan: 'Smart plan',
  emptyTodayT: 'Nothing planned today', emptyTodayS: 'Add a task, or plan an exam and Nazzim fills your days.',
  secAccount: 'ACCOUNT', secStudy: 'STUDY', secApp: 'APP', subjExam: 'Exam {d}', subjTasks: '{n} open tasks', subjTask1: '1 open task', subjClear: 'Nothing due',
  acTitle: 'Account', acSub: 'Sync and back up your semester', acSignIn: 'Sign in', acCreate: 'Create account',
  acBenefits: ['Your semester on every device', 'Backed up if you lose your phone', 'Works offline, syncs when you’re back'],
  acEmail: 'Email', acPassword: 'Password (8+ characters)', acToCreate: 'New here? Create an account', acToSignIn: 'Have an account? Sign in',
  acConfirm: 'Check your inbox and confirm your email, then sign in here.', acLocalNote: 'Without an account, your data stays on this device only.',
  acErr: { invalid: 'Email or password is incorrect.', unconfirmed: 'Confirm your email first (check your inbox).', weak: 'Use at least 8 characters.', exists: 'An account with this email already exists. Sign in instead.', network: 'No connection. Try again.', unavailable: 'Sync isn’t set up in this build.', unknown: 'Something went wrong. Try again.' },
  acSynced: 'Synced {t}', acSyncing: 'Syncing…', acSyncError: 'Couldn’t sync. Your changes are safe on this device.', acNever: 'Not synced yet',
  acSyncNow: 'Sync now', acSignOut: 'Sign out', acSignedIn: 'SIGNED IN AS', acJustNow: 'just now', acMinAgo: '{n} min ago',
  obHaveAccount: 'I already have an account', delLocalTitle: 'Erase data on this device?',
  delLocalBody: 'This erases your subjects, exams, plans and progress from this device. This can’t be undone.', toastDelFail: 'Couldn’t delete. Check your connection.',
  xDaysLeft: '{n} DAYS LEFT', xDayLeft: 'TOMORROW', xToday: 'TODAY', xOver: 'DONE', xReadiness: 'Exam readiness',
  xStatus: { onTrack: 'On track', behind: 'A little behind', atRisk: 'Needs focus now', ready: 'Ready', over: 'Exam finished' },
  xStatusSub: { onTrack: 'Keep following the plan.', behind: '{n} sessions slipped. Today’s session catches you up.', atRisk: 'Few days left. Do the next session and the mock test.', ready: 'Light reviews and rest before the exam.', over: 'How did it go? Your work counts toward the semester.' },
  xRemaining: 'Left: {s} sessions · {t}', xPerDay: 'About {m} a day', xNextBtn: 'Start next: {t}', xTopics: 'TOPICS', xPlan: 'STUDY PLAN',
  xTopicState: { notStarted: 'Not started', learning: 'In progress', solid: 'Solid', weak: 'Needs work' },
  xPhase: { learn: 'Phase 1 of 3 · First pass', review: 'Phase 2 of 3 · Reviews', final: 'Phase 3 of 3 · Final prep' },
  xMock: 'Mock test {d}: the best predictor of how the exam will go.', xAdjust: 'Change date or chapters', xDoneN: '{n} done',
  xFocusOn: 'Focus here: {t}',
  obTag: 'From academic chaos to a clear plan.', obStart: 'Get started', obSample: 'Explore with a sample semester',
  obStep: 'Step {n} of 3', obAboutT: 'Where do you study?', obAboutS: 'So plans fit your semester. You can skip any field.',
  obSubjT: 'Your subjects this semester', obSubjS: 'Add each course and the grade you’re aiming for.', obSubjPh: 'e.g. Statistics',
  obExamT: 'Your next exam', obExamS: 'Nazzim turns it into a day-by-day study plan.', obWhich: 'Subject', obWhen: 'When', obChapters: 'Chapters',
  obBuild: 'Let’s build your semester', obNext: 'Next', obSkip: 'Skip', obNoExam: 'No exam coming up yet', noName: 'Student',
  qaTitle: 'Add', qaTask: 'Task or assignment', qaTaskSub: 'Homework, lab report, reading', qaExam: 'Exam',
  qaExamSub: 'Nazzim builds the study plan', qaSubject: 'Subject', qaSubjectSub: 'A course this semester',
  prSemester: 'Semester progress', prConsistency: 'Study consistency', prActive: '{n} of 7 days', prTasks: 'Tasks completed',
  prTasksN: '{d} of {t}', prWeek: 'Focused this week', prSubjects: 'SUBJECT PROGRESS', prReady: 'Exam ready {n}%', prInsights: 'INSIGHTS',
  prWeekBars: 'FOCUS THIS WEEK', prActiveDays: 'Active days', prNoSubjects: 'Add subjects to see progress per course.',
  iAtRisk: '{exam} is in {n} days and readiness is {r}%. Today’s session matters most.', iAtRisk1: '{exam} is tomorrow and readiness is {r}%. Do the mock test today.',
  iBehind: '{n} tasks slipped. Rescue Mode can rebuild your week in a minute.', iUp: '{exam} readiness rose {n}% this week.',
  iHeavier: 'Next week is heavier: {n} planned vs {c} this week. Starting early keeps it calm.', iConsistency: 'You studied on {n} of the last 7 days.',
  iStart: 'Finish one session today and your progress starts here.',
  rescueEyebrow: 'RESCUE PLAN', rescueTitle: 'You’re behind. That’s okay.', rescueSub: 'Nazzim will rebuild the next 7 days around the time you really have.',
  rOverdueN: 'overdue tasks', rExamsN: 'upcoming exams', rWorkN: 'of work this week', capacityL: 'On a normal day I can study',
  buildRescue: 'Build Rescue Plan', applyRescue: 'Apply this plan', rescueNote: 'Deadlines stay the same. Only when you do the work changes.',
  rescueOk: 'This fits your time. {n} items move, nothing is lost.', rescueOnTrack: 'You’re on track. Nothing needs to move.',
  rescueTight: 'Some days still run over. Do the flagged items first, or ask for an extension.', rescueDropped: '{n} extra reviews dropped; later reviews cover them.',
  movedFrom: 'from {d}', tightL: 'Over', toastRescue: 'Plan rebuilt. One step at a time.', rescueMenu: 'Rescue plan',
  behindTitle: 'Things piled up', behindOverdue: '{n} overdue. Let’s rebuild your week.', behindLoad: 'This week is heavier than your usual time.', rebuild: 'Rebuild',
  // Focus linked to work
  sessionComplete: 'Session complete', howWent: 'How did it go? This updates your exam readiness.', taskDoneQ: 'Did you finish the task?',
  yesDone: 'Yes, done', notYet: 'Not yet', focusMin: '{n} min focused', rHard: 'Hard', rOk: 'OK', rEasy: 'Easy',
  // Smart Planner
  plEyebrow: 'SMART PLANNER', plTitle: 'Tell Nazzim what you need.', plSub: 'Your exams, your time, one plan.',
  plPh: 'e.g. Statistics exam in 6 days, I haven’t started', plRun: 'Plan it',
  plTry: ['Statistics exam in 6 days, I haven’t started', 'Calculus final next week, 5 chapters', 'Physics quiz on Thursday'],
  plDays: '{n}-day study plan', plWhy: 'WHY THIS PLAN', plApply: 'Add to my plan', plReplaces: 'Replaces your current {s} plan.',
  plNeed: 'Name the subject and when the exam is, e.g. “Physics exam in 5 days”.', plChapters: 'Chapters', plWhen: 'Exam',
  plNewSubject: 'New subject: {s}', plChapterN: 'Chapter {n}', plR1: 'Starts today, {n} days before the exam.',
  plR2: 'Each chapter comes back after 1, 3 and 7 days, the spacing that makes it stick.', plR3: 'A mock test the day before.',
  plR4: 'About {m} a day, inside your {c}.', plR4over: 'About {m} a day, more than your usual {c}. Start today.',
  plR5: 'Placed around {n} things already on your schedule.', plDone: 'Plan added. Your first session is on Today.',
  toastPlan: '{name} is on (demo, no charge)', toastFree: 'Switched to Free', toastSaved: 'Profile saved', aBack: 'Back',
  aNew: 'New plan', aReset: 'Reset timer', aPlay: 'Start or pause focus', aFinish: 'Finish session', aClose: 'Close',
};

export type Copy = typeof en;

const ar: Copy = {
  appName: 'نظّم', splashTag: 'من الفوضى الأكاديمية إلى خطة واضحة.',
  splashParts: ['الخطة', 'التركيز', 'الامتحانات', 'التقدم'], madeIn: 'صُنع في عُمان', aSkip: 'تخطي',
  dateLine: 'الاثنين · 11 مايو', greet: 'صباح النور، ', now: 'الآن', nowRange: '10:30 – 11:15',
  nowTitle: 'مراجعة الفصل الثالث — التفاضل', nowMeta: 'رياضيات · متبقٍ 35 دقيقة · الامتحان بعد 3 أيام',
  startFocus: 'ابدأ التركيز', markDone: 'تم',
  aiTag: 'ذكاء نظّم · تجريبي', aiLine: 'امتحانك بعد 3 أيام. نقلت أصعب جلسة إلى 10:30 — الساعة التي تركّز فيها أكثر.',
  stream: 'اليوم', kClass: 'محاضرة', kTask: 'مهمة', kFocus: 'تركيز', kHabit: 'عادة',
  plan: 'الخطة', planSub: 'التقويم والمهام والامتحانات — في شاشة واحدة', exams: 'الامتحانات', daysLeft: 'أيام متبقية',
  planExamCta: 'خطط لامتحان جديد بجملة واحدة', weekTasks: 'هذا الأسبوع',
  focus: 'التركيز', focusOn: 'تركّز على', ready: 'جاهز', inFocus: 'في التركيز', paused: 'متوقف',
  sound: 'الصوت', sounds: ['بدون', 'مطر', 'مقهى'], lock: 'إسكات التطبيقات الأخرى', lockSub: 'يحجب التواصل الاجتماعي أثناء التركيز',
  me: 'التقدم', meSub: 'كيف يسير فصلك الدراسي', level: 'المستوى', rank: 'طالب مركّز',
  stFocus: 'ساعات التركيز', stDone: 'مهام منجزة', stTrend: 'عن الأسبوع الماضي',
  week: 'هذا الأسبوع', weekSub: 'دقائق التركيز', habits: 'العادات', habitsHint: 'اضغط على اليوم',
  language: 'اللغة', langValue: 'العربية', proValue: '7 أيام مجاناً',
  appearance: 'المظهر', appearances: ['تلقائي', 'فاتح', 'داكن'],
  accentColor: 'لون التطبيق', accentNames: ['أزرق', 'وردي', 'بنفسجي', 'فيروزي'],
  reminders: 'التذكيرات', remindersSub: 'العادات والامتحانات وجلسات التركيز',
  remHabits: 'تذكير خطة اليوم', remExams: 'العد التنازلي للامتحان', remExamsSub: 'مساء اليوم السابق، الساعة 19:00',
  remFocus: 'انتهاء جلسة التركيز', remFocusSub: 'حتى لو كان نظّم مغلقاً',
  remDenied: 'الإشعارات مغلقة لتطبيق نظّم. فعّلها من الإعدادات › نظّم › الإشعارات.',
  remWeb: 'التذكيرات تعمل في تطبيق الآيفون والآيباد.',
  nHabitTitle: 'خطوتك التالية جاهزة', nHabitBody: 'افتح نظّم لترى ماذا تذاكر الآن.',
  nExamTitle: 'امتحان {name} غداً', nExamBody: 'راجع خطتك ونم قبل منتصف الليل.',
  nFocusTitle: 'اكتملت جلسة التركيز', nFocusBody: '{task} · +50 XP',
  badgesN: ['سلسلة 7 أيام', 'مبكّر', '50 ساعة', 'جاهز للامتحان'],
  cmdTitle: 'ماذا لديك قادماً؟', cmdPh: 'مثلاً: امتحان فيزياء يوم الخميس', tryThis: 'جرّب',
  quick: ['امتحان فيزياء يوم الخميس', 'مهمة: تقرير المختبر قبل الأربعاء', 'نادي رياضي 3 مرات أسبوعياً'],
  building: 'نظّم يبني خطتك…', built: 'بُنيت من جملة واحدة', builtCount: '5 عناصر',
  addAll: 'أضف الكل إلى خطتي',
  gen: [
    ['تلخيص الفصول 4–6', 'اليوم · 16:00 · 40 دقيقة', 'task'],
    ['جلسة حل مسائل 1', 'الثلاثاء · 11:00 · 50 دقيقة', 'focus'],
    ['امتحان سابق 2024', 'الأربعاء · 14:00 · 90 دقيقة', 'task'],
    ['النوم قبل منتصف الليل', 'حتى الخميس', 'habit'],
    ['امتحان الفيزياء', 'الخميس · 09:00 · قاعة C', 'class'],
  ],
  toastTask: 'مهمة منجزة · +20 XP', toastHabit: 'عادة محققة · +10 XP', toastFocus: 'اكتملت الجلسة · +50 XP', toastAdded: 'بُنيت خطة المراجعة · +30 XP',
  tabToday: 'اليوم', tabPlan: 'الخطة', tabFocus: 'التركيز', tabMe: 'التقدم',
  dow: ['ح', 'ن', 'ث', 'ر', 'خ', 'ج', 'س'],
  min: 'دقيقة', of: 'من', done: 'منجز', xpTo: 'XP للمستوى', streakSuffix: ' يوم',
  profile: 'الملف الشخصي', editProfile: 'تعديل الملف', saveProfile: 'حفظ', fName: 'الاسم', fUni: 'الجامعة', fMajor: 'التخصص', fYear: 'السنة',
  defaultName: 'أحمد', defaultUni: 'جامعة السلطان قابوس', defaultMajor: 'علوم الحاسب', defaultYear: 'السنة الثانية',
  dayStreak: 'أيام متتالية', yourPlan: 'باقتك', manage: 'إدارة', upgrade: 'ترقية', memberSince: 'تدرس مع نظّم منذ مايو',
  settings: 'الإعدادات', sGeneral: 'عام', sControls: 'التحكم', sAccount: 'الخصوصية والحساب', version: 'نظّم 1.0.0',
  cHaptics: 'الاهتزاز', cHapticsSub: 'نقرة خفيفة عند إنجاز أي شيء',
  cRewards: 'المكافآت والنقاط', cRewardsSub: 'المستويات والسلاسل والنقاط',
  cAi: 'اقتراحات الذكاء', cAiSub: 'إظهار نصائح ذكاء نظّم في اليوم', cFocusLen: 'مدة التركيز الافتراضية',
  plans: 'الباقات', plansSub: 'ابدأ مجاناً، ورقِّ باقتك عندما يزدحم فصلك الدراسي.', monthly: 'شهري', yearly: 'سنوي',
  tiers: {
    free: { name: 'مجاني', tag: 'خطوتك التالية كل يوم', per: 'دائماً',
      features: ['اليوم: ماذا تفعل الآن', 'المواد والمهام والتركيز المرتبط بها', 'المخطط الذكي لامتحانين نشطين', 'خطة الإنقاذ عند التأخر'] },
    plus: { name: 'Plus', tag: 'لفصل دراسي كامل', per: '',
      features: ['كل ميزات المجاني', 'امتحانات وخطط مذاكرة بلا حدود', 'كل ملاحظات التقدم', 'تذكيرات الامتحانات وخطة اليوم'] },
    pro: { name: 'Pro', tag: 'فصلك الدراسي على وضع تلقائي', per: '',
      features: ['كل ميزات Plus', 'مزامنة التقويم (قريباً)', 'مدرّب مذاكرة ذكي (قريباً)', 'دعم ذو أولوية'] },
  },
  perMonth: '/ شهرياً', perYear: '/ سنوياً', yearNote: '{m} شهرياً، تُدفع سنوياً', save: 'وفّر {n}%', bestValue: 'الأفضل قيمة',
  currentPlan: 'باقتك الحالية', choose: 'اختر {name}', switchFree: 'التحويل إلى المجاني',
  trialCta: 'ابدأ تجربة 7 أيام مجاناً',
  legal: 'مجاناً لمدة 7 أيام، ثم {p}. يتجدد الاشتراك تلقائياً ما لم يُلغَ قبل 24 ساعة على الأقل من نهاية الفترة الحالية. يمكنك الإدارة أو الإلغاء في الإعدادات › Apple ID › الاشتراكات.',
  restore: 'استعادة المشتريات', terms: 'شروط الاستخدام', privacyL: 'سياسة الخصوصية', support: 'الدعم',
  deleteAcc: 'حذف الحساب', delTitle: 'حذف حسابك؟',
  delBody: 'سيتم حذف حسابك وكل موادك وامتحاناتك وخططك وتقدمك نهائياً من خوادم نظّم ومن هذا الجهاز. لا يمكن التراجع عن ذلك.',
  cancel: 'إلغاء', delConfirm: 'حذف نهائي', toastDel: 'تم طلب حذف الحساب',
  exAdd: 'أضف امتحاناً', exNew: 'امتحان جديد', exSubject: 'المادة', exSubjectPh: 'مثلاً: الفيزياء', exDate: 'موعد الامتحان',
  exChapters: 'الفصول أو المواضيع', exChaptersPh: 'كل فصل في سطر، مثلاً:\nالفصل 4\nالفصل 5', exCreate: 'ابنِ خطة مراجعتي',
  exPreview: '{s} جلسة خلال {d} أيام: دراسة كل فصل، ثم مراجعته بعد يوم و3 أيام و7 أيام، ثم امتحان تجريبي في اليوم السابق.',
  exTooSoon: 'اختر موعداً بعد يوم واحد على الأقل.', exNeedsChapters: 'أضف فصلاً واحداً على الأقل.',
  exReady: 'الجاهزية', exLeft: 'متبقٍ {n}', exDelete: 'حذف الامتحان', exDeleteConfirm: 'اضغط مرة أخرى للحذف',
  exNone: 'لا توجد امتحانات بعد. أضف امتحاناً ويخطط نظّم مراجعتك.', exHow: 'مراجعة متباعدة: كل فصل يعود بعد يوم و3 أيام و7 أيام. "صعب" يضيف مراجعة غداً، و"سهل" يلغي واحدة.',
  exChaptersH: 'الفصول', exChaptersN: '{n} فصول', exPlanH: 'خطة المراجعة', exAll: 'كل الفصول', exDay: 'يوم الامتحان',
  kLearn: 'دراسة', kReview: 'مراجعة', kMock: 'امتحان تجريبي', rateQ: 'ما مدى فهمك؟', rates: ['صعب', 'متوسط', 'سهل'],
  reviewsToday: 'مراجعة اليوم', onDay: 'الجدول · {d}', nothingDay: 'لا شيء مخطط. يوم فارغ.', startS: 'ابدأ', doneS: 'تم',
  dToday: 'اليوم', dTomorrow: 'غداً', dIn: 'بعد {n} أيام', toastRated: 'تم الحفظ · +20 XP',
  wd: ['الأحد', 'الاثنين', 'الثلاثاء', 'الأربعاء', 'الخميس', 'الجمعة', 'السبت'], wdLong: ['الأحد', 'الاثنين', 'الثلاثاء', 'الأربعاء', 'الخميس', 'الجمعة', 'السبت'],
  months: ['يناير', 'فبراير', 'مارس', 'أبريل', 'مايو', 'يونيو', 'يوليو', 'أغسطس', 'سبتمبر', 'أكتوبر', 'نوفمبر', 'ديسمبر'],
  sampleExam: { subject: 'الرياضيات', chapters: ['النهايات', 'المشتقات', 'قاعدة السلسلة', 'التكامل'] },
  aiExam: { subject: 'الفيزياء', chapters: ['الفصل 4 · الحركة', 'الفصل 5 · القوى', 'الفصل 6 · الطاقة'] },
  seed: {
    subjects: ['الإحصاء', 'التفاضل والتكامل', 'الفيزياء'], examName: 'الإحصاء',
    chapters: ['الفصل الأول', 'الفصل الثاني', 'الفصل الثالث', 'الفصل الرابع'],
    tasks: ['أسئلة تدريبية على الفصل الثالث', 'تقرير مختبر الفيزياء', 'مسائل التفاضل 2'],
  },
  greetings: ['صباح الخير', 'مساء الخير', 'مساء الخير'], nextMove: 'خطوتك التالية', startSession: 'ابدأ الجلسة',
  rOverdue: 'متأخرة منذ {n} أيام', rOverdue1: 'متأخرة منذ أمس', rExamSoon: 'امتحان {exam} بعد {n} أيام', rExamTomorrow: 'امتحان {exam} غداً',
  rDueToday: 'مستحقة اليوم', rDueTomorrow: 'مستحقة غداً', rPlanned: 'جزء من خطة مذاكرتك',
  nextClear: 'أنجزت كل ما عليك اليوم.', nextClearSub: 'لا شيء مستحق الآن. استرح، أو تقدّم في امتحانك القادم.',
  nextAdd: 'أضف امتحانك الأول', nextAddSub: 'ونظّم يبني لك خطة المذاكرة.',
  overall: 'التقدم العام', todaySchedule: 'جدول اليوم', emptyToday: 'لا شيء في جدول اليوم.',
  load: 'العبء الدراسي', loadLevels: ['خفيف', 'متوسط', 'مرتفع'], loadSub: '{h} مخططة هذا الأسبوع', nextDeadline: 'الموعد القادم',
  kExam: 'امتحان', kTaskB: 'مهمة', kStudyB: 'مذاكرة', markDoneA: 'تحديد كمنجزة',
  tabSubjects: 'المواد', tabMore: 'المزيد', subjects: 'المواد الدراسية', target: 'الهدف {g}', addSubject: 'أضف مادة', newSubject: 'مادة جديدة',
  subjName: 'اسم المادة', subjNamePh: 'مثلاً: الإحصاء', targetGrade: 'الدرجة المستهدفة', colour: 'اللون', icon: 'الأيقونة', create: 'إنشاء',
  progressL: 'التقدم', nextTask: 'المهمة الدراسية التالية', tasksL: 'المهام', pendingN: '{n} متبقية', examsL: 'الامتحانات', upcomingN: '{n} قادمة',
  studyL: 'المذاكرة', sessionsMonth: '{n} جلسات هذا الشهر', addTask: 'أضف مهمة', taskTitlePh: 'مثلاً: أسئلة الفصل الثالث',
  due: 'الموعد', estimate: 'المدة', noSubjects: 'أضف موادك لترى فصلك الدراسي في مكان واحد.', deleteSubject: 'حذف المادة',
  noTasks: 'لا مهام بعد.', examFor: 'المادة', more: 'المزيد', upcomingExams: 'الامتحانات القادمة', progressMenu: 'التقدم',
  inDaysShort: 'بعد {n} أيام', allClear: 'لا شيء متأخر',
  limitExams: 'المجاني يغطي امتحانين نشطين. Plus يخطط لكل امتحاناتك.',
  freeFocus: 'تركيز حر',
  examToday: 'امتحان اليوم', nowL: 'الآن', dayProgress: 'أُنجز {d} من {t} · متبقٍ {m}', dayDone: 'أنجزت كل شيء لليوم',
  glanceSemester: 'الفصل', glanceWeek: 'هذا الأسبوع', glanceExam: 'الامتحان القادم', glanceNone: 'لا يوجد', smartPlan: 'خطة ذكية',
  emptyTodayT: 'لا شيء مخطط اليوم', emptyTodayS: 'أضف مهمة، أو خطط لامتحان ودع نظّم يملأ أيامك.',
  secAccount: 'الحساب', secStudy: 'الدراسة', secApp: 'التطبيق', subjExam: 'امتحان {d}', subjTasks: '{n} مهام مفتوحة', subjTask1: 'مهمة واحدة مفتوحة', subjClear: 'لا شيء مستحق',
  acTitle: 'الحساب', acSub: 'زامن فصلك الدراسي واحفظ نسخة منه', acSignIn: 'تسجيل الدخول', acCreate: 'إنشاء حساب',
  acBenefits: ['فصلك الدراسي على كل أجهزتك', 'نسخة محفوظة إذا فقدت هاتفك', 'يعمل دون إنترنت ويزامن عند عودتك'],
  acEmail: 'البريد الإلكتروني', acPassword: 'كلمة المرور (8 أحرف على الأقل)', acToCreate: 'جديد هنا؟ أنشئ حساباً', acToSignIn: 'لديك حساب؟ سجّل الدخول',
  acConfirm: 'افتح بريدك وأكّد عنوانك، ثم سجّل الدخول هنا.', acLocalNote: 'بدون حساب، تبقى بياناتك على هذا الجهاز فقط.',
  acErr: { invalid: 'البريد أو كلمة المرور غير صحيحة.', unconfirmed: 'أكّد بريدك أولاً (تحقق من صندوق الوارد).', weak: 'استخدم 8 أحرف على الأقل.', exists: 'يوجد حساب بهذا البريد. سجّل الدخول بدلاً من ذلك.', network: 'لا يوجد اتصال. حاول مجدداً.', unavailable: 'المزامنة غير مفعّلة في هذه النسخة.', unknown: 'حدث خطأ ما. حاول مجدداً.' },
  acSynced: 'تمت المزامنة {t}', acSyncing: 'جارٍ المزامنة…', acSyncError: 'تعذّرت المزامنة. تغييراتك محفوظة على هذا الجهاز.', acNever: 'لم تتم المزامنة بعد',
  acSyncNow: 'زامن الآن', acSignOut: 'تسجيل الخروج', acSignedIn: 'مسجّل باسم', acJustNow: 'الآن', acMinAgo: 'قبل {n} دقيقة',
  obHaveAccount: 'لدي حساب بالفعل', delLocalTitle: 'مسح البيانات من هذا الجهاز؟',
  delLocalBody: 'سيتم مسح موادك وامتحاناتك وخططك وتقدمك من هذا الجهاز. لا يمكن التراجع عن ذلك.', toastDelFail: 'تعذّر الحذف. تحقق من الاتصال.',
  xDaysLeft: 'متبقٍ {n} أيام', xDayLeft: 'غداً', xToday: 'اليوم', xOver: 'انتهى', xReadiness: 'الجاهزية للامتحان',
  xStatus: { onTrack: 'على المسار', behind: 'متأخر قليلاً', atRisk: 'يحتاج تركيزاً الآن', ready: 'جاهز', over: 'انتهى الامتحان' },
  xStatusSub: { onTrack: 'استمر على الخطة.', behind: 'فاتتك {n} جلسات. جلسة اليوم تعيدك للمسار.', atRisk: 'أيام قليلة متبقية. أنجز الجلسة التالية والاختبار التجريبي.', ready: 'مراجعات خفيفة وراحة قبل الامتحان.', over: 'كيف كان؟ عملك محسوب في تقدم فصلك.' },
  xRemaining: 'متبقٍ: {s} جلسات · {t}', xPerDay: 'حوالي {m} يومياً', xNextBtn: 'ابدأ التالي: {t}', xTopics: 'المواضيع', xPlan: 'خطة المذاكرة',
  xTopicState: { notStarted: 'لم يبدأ', learning: 'قيد التقدم', solid: 'متمكن', weak: 'يحتاج عملاً' },
  xPhase: { learn: 'المرحلة 1 من 3 · القراءة الأولى', review: 'المرحلة 2 من 3 · المراجعات', final: 'المرحلة 3 من 3 · الاستعداد النهائي' },
  xMock: 'الاختبار التجريبي {d}: أفضل مؤشر على أدائك في الامتحان.', xAdjust: 'غيّر الموعد أو الفصول', xDoneN: 'أُنجز {n}',
  xFocusOn: 'ركّز هنا: {t}',
  obTag: 'من الفوضى الأكاديمية إلى خطة واضحة.', obStart: 'ابدأ', obSample: 'استكشف بفصل دراسي تجريبي',
  obStep: 'الخطوة {n} من 3', obAboutT: 'أين تدرس؟', obAboutS: 'لتناسب الخطط فصلك الدراسي. يمكنك تخطي أي حقل.',
  obSubjT: 'موادك هذا الفصل', obSubjS: 'أضف كل مقرر والدرجة التي تطمح لها.', obSubjPh: 'مثلاً: الإحصاء',
  obExamT: 'امتحانك القادم', obExamS: 'يحوّله نظّم إلى خطة مذاكرة يوماً بيوم.', obWhich: 'المادة', obWhen: 'الموعد', obChapters: 'الفصول',
  obBuild: 'لنبنِ فصلك الدراسي', obNext: 'التالي', obSkip: 'تخطي', obNoExam: 'لا يوجد امتحان قريب بعد', noName: 'طالب',
  qaTitle: 'إضافة', qaTask: 'مهمة أو واجب', qaTaskSub: 'واجب، تقرير مختبر، قراءة', qaExam: 'امتحان',
  qaExamSub: 'نظّم يبني خطة المذاكرة', qaSubject: 'مادة', qaSubjectSub: 'مقرر في هذا الفصل',
  prSemester: 'تقدم الفصل', prConsistency: 'الانتظام في المذاكرة', prActive: '{n} من 7 أيام', prTasks: 'المهام المنجزة',
  prTasksN: '{d} من {t}', prWeek: 'تركيز هذا الأسبوع', prSubjects: 'تقدم المواد', prReady: 'جاهزية الامتحان {n}%', prInsights: 'ملاحظات',
  prWeekBars: 'التركيز هذا الأسبوع', prActiveDays: 'أيام نشطة', prNoSubjects: 'أضف موادك لترى تقدم كل مادة.',
  iAtRisk: 'امتحان {exam} بعد {n} أيام وجاهزيتك {r}%. جلسة اليوم هي الأهم.', iAtRisk1: 'امتحان {exam} غداً وجاهزيتك {r}%. اختبر نفسك اليوم.',
  iBehind: 'تأخرت {n} مهام. خطة الإنقاذ تعيد ترتيب أسبوعك في دقيقة.', iUp: 'ارتفعت جاهزية {exam} بنسبة {n}% هذا الأسبوع.',
  iHeavier: 'الأسبوع القادم أثقل: {n} مخطط مقابل {c} هذا الأسبوع. البدء مبكراً يبقيه هادئاً.', iConsistency: 'ذاكرت في {n} من آخر 7 أيام.',
  iStart: 'أنهِ جلسة واحدة اليوم وسيبدأ تقدمك من هنا.',
  rescueEyebrow: 'خطة الإنقاذ', rescueTitle: 'متأخر قليلاً؟ لا بأس.', rescueSub: 'سيعيد نظّم بناء الأيام السبعة القادمة حسب وقتك الحقيقي.',
  rOverdueN: 'مهام متأخرة', rExamsN: 'امتحانات قادمة', rWorkN: 'عمل هذا الأسبوع', capacityL: 'في اليوم العادي أستطيع المذاكرة',
  buildRescue: 'ابنِ خطة الإنقاذ', applyRescue: 'طبّق الخطة', rescueNote: 'المواعيد النهائية لا تتغير، يتغير فقط وقت إنجاز العمل.',
  rescueOk: 'الخطة تناسب وقتك. سيتم نقل {n} عناصر دون أن يضيع شيء.', rescueOnTrack: 'أنت على المسار. لا شيء يحتاج إلى نقل.',
  rescueTight: 'بعض الأيام ما زالت مزدحمة. ابدأ بالعناصر المعلّمة، أو اطلب تمديداً.', rescueDropped: 'حُذفت {n} مراجعات إضافية، والمراجعات اللاحقة تغطيها.',
  movedFrom: 'من {d}', tightL: 'زائد', toastRescue: 'أُعيد بناء خطتك. خطوة بخطوة.', rescueMenu: 'خطة الإنقاذ',
  behindTitle: 'تراكمت الأمور', behindOverdue: '{n} متأخرة. لنُعد ترتيب أسبوعك.', behindLoad: 'هذا الأسبوع أثقل من وقتك المعتاد.', rebuild: 'أعد الترتيب',
  sessionComplete: 'انتهت الجلسة', howWent: 'كيف كانت؟ هذا يحدّث جاهزيتك للامتحان.', taskDoneQ: 'هل أنهيت المهمة؟',
  yesDone: 'نعم، أنهيتها', notYet: 'ليس بعد', focusMin: '{n} دقيقة تركيز', rHard: 'صعبة', rOk: 'جيدة', rEasy: 'سهلة',
  plEyebrow: 'المخطط الذكي', plTitle: 'أخبر نظّم بما تحتاجه.', plSub: 'امتحاناتك ووقتك في خطة واحدة.',
  plPh: 'مثلاً: عندي اختبار Statistics بعد 6 أيام ولم أبدأ', plRun: 'خطّط',
  plTry: ['عندي اختبار Statistics بعد 6 أيام ولم أبدأ', 'نهائي Calculus الأسبوع القادم، 5 فصول', 'كويز Physics يوم الخميس'],
  plDays: 'خطة مذاكرة لـ {n} أيام', plWhy: 'لماذا هذه الخطة', plApply: 'أضف إلى خطتي', plReplaces: 'تستبدل خطة {s} الحالية.',
  plNeed: 'اذكر المادة وموعد الامتحان، مثلاً: «امتحان فيزياء بعد 5 أيام».', plChapters: 'الفصول', plWhen: 'الامتحان',
  plNewSubject: 'مادة جديدة: {s}', plChapterN: 'الفصل {n}', plR1: 'تبدأ اليوم، قبل الامتحان بـ {n} أيام.',
  plR2: 'كل فصل يعود بعد 1 و3 و7 أيام، وهو التباعد الذي يثبّت المعلومة.', plR3: 'اختبار تجريبي في اليوم السابق.',
  plR4: 'حوالي {m} يومياً، ضمن وقتك ({c}).', plR4over: 'حوالي {m} يومياً، أكثر من وقتك المعتاد ({c}). ابدأ اليوم.',
  plR5: 'وُزّعت حول {n} عناصر موجودة في جدولك.', plDone: 'أُضيفت الخطة. أول جلسة في صفحة اليوم.',
  toastPlan: 'تم تفعيل {name} (تجريبي، بدون دفع)', toastFree: 'تم التحويل إلى المجاني', toastSaved: 'تم حفظ الملف', aBack: 'رجوع',
  aNew: 'خطة جديدة', aReset: 'إعادة المؤقت', aPlay: 'تشغيل أو إيقاف التركيز', aFinish: 'إنهاء الجلسة', aClose: 'إغلاق',
};

export const COPY: Record<Lang, Copy> = { en, ar };

export const kindLabel = (L: Copy, k: Kind) => ({ class: L.kClass, task: L.kTask, focus: L.kFocus, habit: L.kHabit })[k];
