export const dataDict: Record<string, string> = {
  "أنظمة إنتاجية رقمية": "Digital productivity systems",
  "خصم 25٪ على النظام الكامل — وصول رقمي فوري": "25% off the Complete System — instant digital access",
  "تحميل رقمي فوري": "Instant digital download",
  "نظّم يومك.": "Organize your day.",
  "أنجز ما يهمك.": "Achieve what matters.",
  "أنظمة إنتاجية رقمية جاهزة تساعدك على تنظيم مهامك، بناء عاداتك، ومتابعة أهدافك — ببساطة وبدون تعقيد.": "Ready-made digital productivity systems that help you organize your tasks, build your habits, and track your goals — simply, with no complexity.",
  "استكشف الأنظمة": "Explore the systems",
  "كيف يعمل نظّم؟": "How does Nazzim work?",
  "تتبع واضح للتقدم": "Clear progress tracking",
  "مهامك وعاداتك وأهدافك معروضة بصرياً، لتعرف موقعك بنظرة واحدة بدل التخمين.": "Your tasks, habits, and goals shown visually, so you know where you stand at a glance instead of guessing.",
  "هيكل يومي وأسبوعي": "Daily and weekly structure",
  "تخطيط بسيط يساعدك على ترتيب يومك والبقاء مركزاً دون إرهاق أو أدوات معقدة.": "Simple planning that keeps your day organized and your focus sharp, without burnout or complicated tools.",
  "استمرارية لا حماس مؤقت": "Consistency, not temporary motivation",
  "التسجيل اليومي القصير يحوّل الالتزام إلى عادة، فتصبح الإنتاجية أسهل مع الوقت.": "A short daily check-in turns commitment into habit, making productivity easier over time.",
  "مرن مع حياتك": "Flexible around your life",
  "عدّل الأقسام والعادات والمهام كما تشاء — النظام يتكيّف مع روتينك لا العكس.": "Edit sections, habits, and tasks however you like — the system adapts to your routine, not the other way around.",
  "يا ابن آدم، إنما أنت أيام، فإذا ذهب يومك، ذهب بعضك.": "O child of Adam, you are but days; when a day passes, a part of you passes with it.",
  "الحسن البصري": "Al-Hasan al-Basri",
  "إمام وتابعي": "Imam and Tabi'i scholar",
  "النجاح ليس قفزة مفاجئة، بل حصيلة مجهودات صغيرة وعادات بسيطة تتراكم يوماً بعد يوم.": "Success is not a sudden leap, but the sum of small efforts and simple habits that build up day after day.",
  "فهد عامر الأحمدي": "Fahd Amer Al-Ahmadi",
  "كاتب ومؤلف": "Writer and author",
  "التحسين اليومي المستمر ولو بنسبة بسيطة، هو ما يصنع النجاحات العظيمة على المدى الطويل.": "Continuous daily improvement, even by a small margin, is what creates great success in the long run.",
  "أحمد الشقيري": "Ahmed Al-Shugairi",
  "إعلامي وصانع محتوى": "Media personality and content creator",
  "متتبع المهام": "Task Tracker",
  "أدر مهام يومك بوضوح لتنجز أكثر بجهد أقل، مع تواريخ تتحدث تلقائياً لشهر كامل.": "Manage your day's tasks with clarity and get more done with less effort, with dates that auto-update for a full month.",
  "متتبع العادات": "Habit Tracker",
  "لوحة بصرية تساعدك على الاستمرارية وتتبع عاداتك الشهرية، مع رسوم تعرض نسبة تقدمك.": "A visual board that helps you stay consistent and track your monthly habits, with charts showing your progress.",
  "متتبع الأهداف": "Goal Tracker",
  "قسّم أهدافك الكبرى إلى خطوات صغيرة، وتابع إنجازها خطوة بخطوة.": "Break your big goals into small steps, and track their completion step by step.",
  "تعرف تقدمك بنظرة واحدة": "See your progress at a glance",
  "لوحات ورسوم تعرض التزامك بعاداتك وإنجاز مهامك ونسبة تقدمك في أهدافك، بدون حساب يدوي.": "Boards and charts showing your habit consistency, task completion, and goal progress — with no manual calculation.",
  "يوم مرتّب بدون تعقيد": "An organized day, without complexity",
  "هيكل بسيط لتخطيط يومك وأسبوعك، يبقيك متحكماً بجدولك بدل أن تتحكم به المهام.": "A simple structure for planning your day and week, keeping you in control of your schedule instead of your tasks controlling you.",
  "التزام يتحول إلى عادة": "Commitment that turns into habit",
  "دقائق قصيرة يومياً للتسجيل والمتابعة كافية لتثبيت الروتين على المدى الطويل.": "A few short minutes a day to log and follow up is enough to lock in a long-term routine.",
  "نظام واحد لحياتك وعملك": "One system for your life and work",
  "بدل أدوات متفرقة، كل شيء في مكان واحد يمكنك تعديله ليناسبك تماماً.": "Instead of scattered tools, everything lives in one place you can customize to fit you exactly.",
  "اختر نظامك": "Choose your system",
  "أداة واحدة تحل مشكلتك الحالية، أو النظام الكامل.": "One tool to solve your current problem, or the Complete System.",
  "أتمم الطلب": "Complete your order",
  "دفعة واحدة، ثم يظهر لك رابط الملف فوراً.": "One-time payment, then your file link appears instantly.",
  "انسخ وابدأ": "Copy and start",
  "«إنشاء نسخة» في Google Sheets، وتبدأ التنظيم في دقائق.": "Click \"Make a copy\" in Google Sheets, and start organizing within minutes.",
  "تابع عاداتك اليومية في لوحة واحدة، وشاهد استمراريتك تكبر شهراً بعد شهر.": "Track your daily habits in one board, and watch your consistency grow month after month.",
  "نظام لمتابعة العادات داخل Google Sheets. تحدد عاداتك مرة واحدة، تسجّل التزامك كل يوم بنقرة، وترى نسبة استمراريتك في لوحة بصرية واضحة — بدون إعدادات معقدة ولا تطبيقات إضافية.": "A habit-tracking system built in Google Sheets. Set your habits once, log your commitment daily with one click, and see your consistency in a clear visual board — no complex setup, no extra apps.",
  "من يبدأ عادة جديدة ويريد ألا يفقد الاستمرارية": "Anyone starting a new habit who wants to stay consistent",
  "من يفضّل لوحة بصرية بسيطة على التطبيقات المزدحمة": "Anyone who prefers a simple visual board over cluttered apps",
  "تابع عاداتك الشهرية في شبكة واحدة تُقرأ بنظرة واحدة": "Track your monthly habits in a single grid readable at a glance",
  "اعرف نسبة التزامك بكل عادة عبر رسوم تتحدث تلقائياً": "See your commitment rate for each habit with auto-updating charts",
  "لا تفقد سلسلة الاستمرارية — الأيام المنجزة تظهر بوضوح": "Never lose your streak — completed days are clearly displayed",
  "عدّل العادات وأضف غيرها في أي وقت بدون كسر الملف": "Edit or add habits anytime without breaking the file",
  "ملف Google Sheets جاهز — انسخه وابدأ": "A ready-made Google Sheets file — copy it and start",
  "صفحة إعداد سريعة لعاداتك": "A quick setup page for your habits",
  "تعليمات استخدام مختصرة بالعربية داخل الملف": "Brief usage instructions in Arabic inside the file",
  "حساب Google": "A Google account",
  "متصفح حديث": "A modern browser",
  "لا يحتاج اشتراكاً شهرياً": "No monthly subscription needed",
  "نظّم مهام يومك، وحوّل أهدافك الكبيرة إلى خطوات صغيرة يمكن إنجازها.": "Organize your day's tasks, and turn your big goals into small, achievable steps.",
  "نظام يجمع إدارة المهام مع متابعة الأهداف في ملف واحد. تكتب مهام يومك وترتّبها بالأولوية، وتربطها بأهدافك حتى يبقى عملك اليومي متصلاً بما يهمك فعلاً. التواريخ تتحدث تلقائياً لشهر كامل بعد إدخال الشهر والسنة مرة واحدة.": "A system that combines task management with goal tracking in one file. Write your daily tasks, prioritize them, and link them to your goals so your daily work stays connected to what really matters. Dates auto-update for a full month once you enter the month and year.",
  "من يريد يوماً واضحاً بلا قوائم مبعثرة": "Anyone who wants a clear day without scattered lists",
  "من لديه أهداف كبيرة ويحتاج تقسيمها إلى خطوات": "Anyone with big goals who needs to break them into steps",
  "أدر مهام يومك بأولويات وحالات واضحة، لتنجز أكثر بجهد أقل": "Manage your day's tasks with clear priorities and statuses, and get more done with less effort",
  "تواريخ شهر كامل تتحدث تلقائياً بمجرد إدخال الشهر والسنة": "A full month of dates that auto-update once you enter the month and year",
  "قسّم كل هدف إلى خطوات صغيرة قابلة للتنفيذ": "Break each goal into small, actionable steps",
  "تابع نسبة تقدمك في كل هدف بدون حساب يدوي": "Track your progress on each goal without manual calculation",
  "صفحة مهام وصفحة أهداف مرتبطتان": "A linked tasks page and goals page",
  "المهام والعادات والأهداف في نظام واحد متكامل — بسعر أقل من شرائها منفصلة.": "Tasks, habits, and goals in one complete system — at a lower price than buying them separately.",
  "النظام الكامل من نظّم: العادات والمهام والأهداف داخل نظام واحد متسق، مع لوحة تجمع صورة أسبوعك في مكان واحد. مناسب لمن يريد نظاماً واحداً يدير به حياته وعمله بدل أدوات متفرقة.": "Nazzim's Complete System: habits, tasks, and goals within one consistent system, with a dashboard that brings your entire week into one view. Ideal for anyone who wants a single system to manage life and work instead of scattered tools.",
  "من يريد نظاماً واحداً لكل شيء بدل ملفات متفرقة": "Anyone who wants one system for everything instead of scattered files",
  "من يخطط لعمله ودراسته وحياته في نفس المكان": "Anyone who plans their work, studies, and life in the same place",
  "كل أدوات نظّم في نظام واحد: مهام، عادات، أهداف": "All of Nazzim's tools in one system: tasks, habits, goals",
  "لوحة واحدة تعرض صورة أسبوعك كاملة": "One dashboard showing your entire week",
  "انتقال سلس بين التخطيط اليومي والمتابعة الشهرية": "Seamless transition between daily planning and monthly tracking",
  "قيمة أفضل من شراء الأدوات منفصلة": "Better value than buying the tools separately",
  "لوحة رئيسية تجمع الصورة الكاملة": "A main dashboard bringing the full picture together",
  "الأفضل قيمة": "Best value",
  "وصول رقمي فوري": "Instant digital access",
  "الروابط تظهر لك بعد إتمام الدفع مباشرة.": "Your links appear immediately after payment.",
  "يعمل داخل Google Sheets": "Works inside Google Sheets",
  "انسخ الملف إلى حسابك وابدأ — بلا تثبيت.": "Copy the file to your account and start — no installation.",
  "شراء مرة واحدة": "One-time purchase",
  "دفعة واحدة، بدون اشتراك شهري.": "A single payment, no monthly subscription.",
  "بسيط من أول يوم": "Simple from day one",
  "تعليمات مختصرة داخل الملف، بلا خبرة مسبقة.": "Brief instructions inside the file, no prior experience needed.",
  "متابعة العادات": "Habit tracking",
  "إدارة المهام اليومية": "Daily task management",
  "متابعة الأهداف": "Goal tracking",
  "شراء مرة واحدة بدون اشتراك": "One-time purchase, no subscription",
  "هل نظّم تطبيق أحمّله؟": "Is Nazzim an app I need to download?",
  "لا. أنظمة نظّم الحالية ملفات رقمية تعمل داخل Google Sheets، تفتحها من المتصفح بدون أي تثبيت.": "No. Nazzim's current systems are digital files that run inside Google Sheets — you open them from your browser with no installation.",
  "ماذا أحصل عليه بعد الدفع؟": "What do I get after paying?",
  "بعد إتمام الدفع يظهر لك رابط الملف مباشرة. تفتح الرابط، تختار «إنشاء نسخة» (Make a copy)، فتصبح لديك نسختك الخاصة وتبدأ الاستخدام.": "As soon as payment is complete, your file link appears. Open the link, choose \"Make a copy,\" and you'll have your own copy ready to use.",
  "هل أحتاج خبرة في Google Sheets؟": "Do I need experience with Google Sheets?",
  "لا. كل ملف مصمم ليكون سهل الاستخدام، ويحتوي بداخله على تعليمات واضحة وخطوات مباشرة للبدء.": "No. Every file is designed to be easy to use, with clear instructions and simple steps to get started included inside.",
  "هل أحتاج حساب Google؟": "Do I need a Google account?",
  "نعم، تحتاج حساب Google مجاني لإنشاء نسختك الخاصة من الملف والاحتفاظ بتغييراتك.": "Yes, you need a free Google account to create your own copy of the file and save your changes.",
  "هل يعمل على الهاتف؟": "Does it work on mobile?",
  "يمكن فتح الملف على الهاتف عبر تطبيق Google Sheets، لكن التجربة الأوسع تكون على شاشة الحاسب لأن الملفات تعرض جداول ورسوماً.": "You can open the file on your phone via the Google Sheets app, but the fuller experience is on a computer screen since the files display tables and charts.",
  "هل يمكنني التعديل على الملف؟": "Can I edit the file?",
  "نعم. النسخة ملكك: يمكنك تعديل أسماء العادات والمهام والأقسام بما يناسب روتينك.": "Yes. Your copy is fully yours — you can rename habits, tasks, and sections to fit your routine.",
  "هل أحتاج اشتراكاً شهرياً؟": "Do I need a monthly subscription?",
  "لا. الشراء لمرة واحدة، ولا توجد رسوم متكررة.": "No. It's a one-time purchase with no recurring fees.",
  "ماذا لو دفعت ولم يعمل الملف؟": "What if I pay and the file doesn't work?",
  "تواصل معنا وسنحل المشكلة أو نرسل نسخة بديلة. وإذا تعذّر الحل، يُعاد إليك المبلغ بالكامل.": "Contact us and we'll resolve the issue or send a replacement copy. If it can't be resolved, you'll receive a full refund.",
  "هل يمكنني استخدامه لأكثر من شخص؟": "Can I use it for more than one person?",
  "الترخيص لاستخدام شخصي واحد. للاستخدام داخل فريق أو مؤسسة، تواصل معنا لترتيب ذلك. (نص قابل للتعديل عند إقرار سياسة الترخيص النهائية)": "The license is for a single personal use. For team or organization use, contact us to arrange it. (Text editable once the final licensing policy is set.)",
  "هل يوجد استرجاع؟": "Is there a refund policy?",
  "المنتجات رقمية ويتم الوصول إليها فوراً. راجع صفحة سياسة الاسترجاع للتفاصيل، وهي قابلة للتحديث لتطابق سياسة المتجر النهائية.": "Products are digital and delivered instantly. See the refund policy page for details; it is subject to updates to match the store's final policy.",
  "سارة": "Sarah",
  "جربت تطبيقات كثيرة ولم أستمر بأي منها. هذا أول نظام التزمت به فعلاً — بسيط وواضح ويعمل.": "I tried many apps and never stuck with any of them. This is the first system I've actually kept up with — simple, clear, and it works.",
  "عبدالله": "Abdullah",
  "أفضل ما فيه أنه لا يطلب مني إعداداً طويلاً. نسخت الملف وبدأت في خمس دقائق.": "The best part is it doesn't require a long setup. I copied the file and got started in five minutes.",
  "منى": "Mona",
  "لوحة الأسبوع غيّرت طريقتي في التخطيط. أرى تقدمي بدون أن أفكر في الحساب.": "The weekly dashboard changed how I plan. I see my progress without ever thinking about calculations.",
};
